#!/usr/bin/env node
// gen_wire_gunner_ref.mjs — bundle the wire-gunner TS reference for the generic
// differential harness (oracle-workstream-plan.md §1.3: "the same bundling path
// serves the generic harness" — esbuild, like the PoC's sourceDamage.ts -> oracle.mjs).
//
// Seam-spy aliasing: the reference's OWN seams — startStream/tickStream
// (rom/stream-vm.ts) and the cue dispatchers (rom/dispatch.ts) — are replaced by a
// recording spy module, the TS-side analogue of the wasm-side zz_* import shims.
// Both sides are cut at the SAME ROM function boundary (zz_004beb8_ <-> startStream,
// zz_004cd24_ <-> tickStream), so the differential compares the units' decisions,
// not the (out-of-unit) stream VM internals.
//
// Staleness binding (harness F4 pattern): the bundle embeds sha256 of the
// LF-normalized wire-gunner.ts; specs refuse to run if the live file drifted.
// Regenerate with:  node gen_wire_gunner_ref.mjs
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..", "..", "..");

// Repo uses a pnpm store; resolve esbuild through it (no direct node_modules/esbuild).
async function loadEsbuild() {
  try { return (await import("esbuild")).default ?? (await import("esbuild")); } catch { /* fall through */ }
  const pnpm = path.join(root, "node_modules", ".pnpm");
  const hit = fs.readdirSync(pnpm).find((d) => /^esbuild@/.test(d));
  if (!hit) throw new Error("esbuild not found (node_modules/.pnpm)");
  const mod = await import("file:///" + path.join(pnpm, hit, "node_modules", "esbuild", "lib", "main.js").replace(/\\/g, "/"));
  return mod.default ?? mod;
}
const esbuild = await loadEsbuild();
const srcPath = path.join(root, "packages", "combat", "src", "families", "wire-gunner.ts");
const outPath = path.join(here, "refs", "wire-gunner-ref.mjs");

const srcNormalized = fs.readFileSync(srcPath).toString("utf8").replace(/\r\n/g, "\n");
const srcSha = createHash("sha256").update(Buffer.from(srcNormalized, "utf8")).digest("hex");

const SPY = `
export const __seamLog = [];
export function __resetSeams() { __seamLog.length = 0; }
export function startStream(actor, mask, group, slot, rate = -1.0) {
  __seamLog.push({ seam: "stream_arm", mask, group, slot, rate });
}
export function tickStream(actor, mask, ctx = {}) {
  __seamLog.push({ seam: "stream_tick", mask });
  return false;
}
export function dispatchFullBodyCue(actor, cueId) {
  __seamLog.push({ seam: "fb_cue", cue: cueId });
  return false;
}
export function dispatchUpperBodyCue(actor, cueId) {
  __seamLog.push({ seam: "ub_cue", cue: cueId });
  return false;
}
`;

const ENTRY = `
export { createWireGunnerRootAction, configureWireGunnerFamily, WIRE_GUNNER_X } from ${JSON.stringify(srcPath.replace(/\\/g, "/"))};
export { __seamLog, __resetSeams } from "seam-spy";
export const __source_sha256 = ${JSON.stringify(srcSha)};
export const __source = "packages/combat/src/families/wire-gunner.ts";
`;

const seamSpyPlugin = {
  name: "seam-spy",
  setup(build) {
    build.onResolve({ filter: /(^seam-spy$)|(\/rom\/stream-vm\.js$)|(\/rom\/dispatch\.js$)|(^\.\.\/rom\/(stream-vm|dispatch)\.js$)/ },
      () => ({ path: "seam-spy", namespace: "seam-spy" }));
    build.onLoad({ filter: /.*/, namespace: "seam-spy" }, () => ({ contents: SPY, loader: "js" }));
  },
};

const result = await esbuild.build({
  stdin: { contents: ENTRY, resolveDir: here, loader: "js" },
  bundle: true,
  format: "esm",
  platform: "neutral",
  write: false,
  plugins: [seamSpyPlugin],
});
const banner = `// GENERATED by gen_wire_gunner_ref.mjs — do not edit. Source: packages/combat/src/families/wire-gunner.ts (sha256 ${srcSha})\n// stream-vm.ts/dispatch.ts are aliased to a recording seam spy (see generator header).\n`;
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, banner + result.outputFiles[0].text);
console.log("wrote", outPath, "source sha256", srcSha);
