#!/usr/bin/env python3
"""gen_spike_host.py -- generate the embedder for the recompiled function.

The recompiled C (ppc_recomp.py output) is pure translation and knows nothing
about the game.  Everything game- or host-specific lives here, and this file
makes each of those inputs explicit so the spike's claim can be audited:

  1. THE ENTRY-POINT TABLE.  address -> host adapter, for the SDK callees this
     function reaches.  Addresses come from the console capture's own binding
     map; the ARITY of each GX entry point comes from the project's existing,
     hand-written, ROM-independent SDK declaration file
     packages/rom-runtime/test/fixtures/gx-rom-unit/gnt4_gx_decls.h.  This is
     the SDK seam the port already has (docs/gx-hle-host.md), not a per-function
     port artifact.

  2. THE ARENA SEED.  The console's own memory at the addresses it read during
     the capture, replayed into the recompiler's MEM1.  Same input the existing
     harness uses (`seeded_bytes` in the result artifact).

  3. THE MACHINE STATE AT ENTRY.  r13 (the small-data-area base) is read out of
     the ROM's own __init_registers, NOT out of the capture.  r1 is set to an
     address of OUR choosing, deliberately different from the console's, so
     that a stack-pointer argument can only match structurally -- which is the
     point being tested.

Nothing else is supplied.  In particular no signature, no parameter list, no
type and no return value for the recompiled function itself.
"""
from __future__ import annotations

import argparse
import base64
import json
import re
import struct
from pathlib import Path


def parse_decls(path):
    """name -> parameter count, from the SDK declaration header."""
    text = Path(path).read_text()
    out = {}
    for m in re.finditer(r"\bvoid\s+(\w+)\s*\(([^)]*)\)\s*;", text):
        name, params = m.group(1), m.group(2).strip()
        if params in ("", "void"):
            out[name] = 0
        else:
            out[name] = len([p for p in params.split(",") if p.strip()])
    return out


TEMPLATE = r"""/* GENERATED by research/tools/static-recomp/gen_spike_host.py -- do not edit.
 *
 * The embedder for the statically recompiled %(fn)s.  See that script's
 * docstring for exactly what is supplied here and what is not.
 */
#include "ppc_rt.h"

#include <stdio.h>
#include <stdlib.h>

/* --- the recompiled function ------------------------------------------- */
void %(cname)s(ppc_ctx *);

/* --- event log ---------------------------------------------------------- */

static void emit_call(ppc_ctx *c, const char *name, int nargs)
{
    printf("{\"k\":\"call\",\"at\":\"0x%%08x\",\"callee\":\"%%s\",\"sp\":\"0x%%08x\",\"args\":[",
           c->cia, name, c->r[1]);
    for (int i = 0; i < nargs; i++)
        printf("%%s%%u", i ? "," : "", c->r[3 + i]);
    printf("]}\n");
}

void gf_host_wgpipe(ppc_ctx *c, uint32_t value, int width, int is_float)
{
    printf("{\"k\":\"wgpipe\",\"at\":\"0x%%08x\",\"width\":%%d,\"value\":%%u,\"float\":%%d}\n",
           c->cia, width, value, is_float);
}

uint32_t gf_host_mmio_load(ppc_ctx *c, uint32_t ea, int width)
{
    ppc_fault("unmodelled MMIO load", ea, (uint32_t)width);
    return 0;
}

/* --- SDK adapters ------------------------------------------------------- */
%(adapters)s

/* --- the whole-program entry-point table --------------------------------
 * A `bl` is a lookup by constant here; a `bctrl` is the same lookup with a
 * runtime value (ppc_rt.c:ppc_bctrl).  Growing a port means adding rows. */
struct ppc_entry { uint32_t addr; ppc_fn fn; const char *name; };
static const struct ppc_entry ppc_entries[] = {
%(entries)s};

ppc_fn ppc_lookup(uint32_t addr)
{
    for (unsigned i = 0; i < sizeof(ppc_entries) / sizeof(ppc_entries[0]); i++)
        if (ppc_entries[i].addr == addr) return ppc_entries[i].fn;
    return 0;
}

/* --- arena seed ---------------------------------------------------------
 * The console's OWN bytes, at the console's OWN addresses, big-endian, exactly
 * as MEM1 held them.  %(seed_note)s */
struct seed { uint32_t addr; uint32_t len; const unsigned char *bytes; };
%(seed_blobs)s
static const struct seed seeds[] = {
%(seed_rows)s};

/* --- run ---------------------------------------------------------------- */

#define GF_SDA_BASE 0x%(sda)08xu   /* r13, from the ROM's own __init_registers
                                    * at 0x%(sda_at)08x -- NOT from the capture */
#define GF_STACK_TOP 0x%(stack)08xu /* deliberately NOT the console's r1 */

int main(void)
{
    ppc_mem1 = (uint8_t *)calloc(1, PPC_MEM1_SIZE);
    if (!ppc_mem1) return 1;

    for (int inv = 0; inv < %(invocations)d; inv++) {
        for (unsigned i = 0; i < sizeof(seeds) / sizeof(seeds[0]); i++)
            for (uint32_t j = 0; j < seeds[i].len; j++)
                ppc_mem1[(seeds[i].addr & 0x03FFFFFFu) + j] = seeds[i].bytes[j];

        ppc_ctx ctx;
        memset(&ctx, 0, sizeof ctx);
        ctx.r[13] = GF_SDA_BASE;
        ctx.r[1] = GF_STACK_TOP;
        ctx.lr = 0xDEADBEEFu;

        printf("{\"k\":\"invocation\",\"n\":%%d,\"entry_sp\":\"0x%%08x\"}\n", inv, ctx.r[1]);
        %(cname)s(&ctx);
        printf("{\"k\":\"exit\",\"n\":%%d,\"exit_sp\":\"0x%%08x\"}\n", inv, ctx.r[1]);
    }
    return 0;
}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--capture", required=True)
    ap.add_argument("--decls", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--sda", default="0x8043b5a0")
    ap.add_argument("--sda-at", default="0x80003334")
    ap.add_argument("--stack", default="0x81200000")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    lines = Path(a.capture).read_text().splitlines()
    header = json.loads(lines[0])
    invs = [json.loads(l) for l in lines[1:] if l.strip()]
    manifest = json.loads(Path(a.manifest).read_text())
    arity = parse_decls(a.decls)

    binding = header["binding"]["map"]
    adapters, entries = [], []
    for addr, name in binding.items():
        n = arity.get(name)
        if n is None:
            raise SystemExit("no declaration for %s in %s" % (name, a.decls))
        adapters.append('static void ad_%s(ppc_ctx *c) { emit_call(c, "%s", %d); }'
                        % (name, name, n))
        entries.append('    { 0x%08xu, ad_%s, "%s" },' % (int(addr, 16), name, name))
    # the recompiled function itself is an entry too -- that is what makes a
    # recompiled program self-contained.
    entries.append('    { %su, %s, "%s" },'
                   % (manifest["entry"], manifest["cname"], manifest["rom_name"]))

    seed_blobs, seed_rows = [], []
    for i, r in enumerate(invs[0]["reads"]):
        raw = base64.b64decode(r["b64"])
        ew = r.get("elem_width", 4)
        # the capture stores element bytes LITTLE-endian (the harness swaps for
        # the wasm's LE linear memory); un-swap back to the console's own
        # big-endian MEM1 image.
        be = b"".join(raw[j:j + ew][::-1] for j in range(0, len(raw), ew))
        seed_blobs.append("static const unsigned char seed_%d[] = {%s};"
                          % (i, ",".join(str(x) for x in be)))
        seed_rows.append("    { 0x%08xu, %d, seed_%d },  /* %s */"
                         % (int(r["addr"], 16), len(be), i, r["name"]))

    src = TEMPLATE % {
        "fn": header["function"]["export"],
        "cname": manifest["cname"],
        "adapters": "\n".join(adapters),
        "entries": "\n".join(entries) + "\n",
        "seed_blobs": "\n".join(seed_blobs),
        "seed_rows": "\n".join(seed_rows) + "\n",
        "seed_note": ("%d region(s) from %s"
                      % (len(seed_rows), Path(a.capture).name)),
        "sda": int(a.sda, 16), "sda_at": int(a.sda_at, 16),
        "stack": int(a.stack, 16),
        "invocations": len(invs),
    }
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(src)
    print("wrote %s: %d adapters, %d entry-table rows, %d seed regions"
          % (a.out, len(adapters), len(entries), len(seed_rows)))


if __name__ == "__main__":
    main()
