import { MELEE, SHOT, SPECIAL } from "./constants.js";
import type { BorgProfile } from "./stats.js";
import type { ProjectileVisualKind } from "./types.js";
import actionProfileData from "./data/actionProfiles.json" with { type: "json" };

export type PrimaryAttackKind = "melee" | "shot";

/** Sword-beam finisher projectile (TUNED design: emitted by the LAST hit of a melee combo
 *  chain; HP damage uses the charge/special damage record plus this multiplier bridge). */
export interface SwordBeamDef {
  speed: number;
  lifetime: number;
  hitRadius: number;
  /** Multiplier applied to the melee swing's raw damage. */
  damageMultiplier: number;
  homingTurn: number;
  visualKind: ProjectileVisualKind;
}

export interface MeleeActionDef {
  startup: number;
  active: number;
  duration: number;
  cooldown: number;
  range: number;
  yTolerance: number;
  damageMultiplier: number;
  knockbackMultiplier: number;
  /** Chain length (1 = no combo). Derived in the generator from distinct exported swing banks. */
  comboHits: number;
  /** Frames after a swing's recovery during which the next chain press still connects. TUNED. */
  comboWindowFrames: number;
  /** Combo-finisher projectile, or null for borgs without a sword beam. */
  swordBeam: SwordBeamDef | null;
}

export interface ShotActionDef {
  cooldown: number;
  recovery: number;
  ammoMax: number;
  reloadFrames: number;
  projectileCount: number;
  spreadRadians: number;
  speed: number;
  lifetime: number;
  homingTurn: number;
  hitRadius: number;
  muzzleForwardOffset: number;
  muzzleYOffset: number;
  damageMultiplier: number;
  hitstunMultiplier: number;
  knockbackMultiplier: number;
  visualKind: ProjectileVisualKind;
  /** Hold-B charge shot: hold accumulates charge frames, release fires a scaled projectile. */
  chargeable: boolean;
  /** Held frames needed for charge tier 1 / tier 2 (tier 2 is also the accumulation cap). */
  chargeTier1Frames: number;
  chargeTier2Frames: number;
  chargeTier1DamageMult: number;
  chargeTier2DamageMult: number;
  /** Ballistic drop applied to the projectile's Y velocity each frame (0 = none). TUNED. */
  bulletDrop: number;
}

export interface SpecialActionDef {
  cooldown: number;
  duration: number;
  radius: number;
  damageMultiplier: number;
  knockbackMultiplier: number;
}

export interface BorgActionProfile {
  primary: PrimaryAttackKind;
  confidence: "medium" | "low" | "fallback";
  melee: MeleeActionDef | null;
  shot: ShotActionDef | null;
  special: SpecialActionDef;
}

type RawActionProfile = {
  primary?: PrimaryAttackKind;
  confidence?: "medium" | "low" | "fallback";
  melee?: Partial<MeleeActionDef> | null;
  shot?: Partial<ShotActionDef> | null;
  special?: Partial<SpecialActionDef> | null;
};

const RAW_PROFILES = actionProfileData.profiles as Record<string, RawActionProfile>;

const DEFAULT_MELEE: MeleeActionDef = {
  startup: MELEE.STARTUP,
  active: MELEE.ACTIVE,
  duration: MELEE.DURATION,
  cooldown: MELEE.COOLDOWN,
  range: MELEE.RANGE,
  yTolerance: MELEE.Y_TOLERANCE,
  damageMultiplier: 1,
  knockbackMultiplier: 1,
  comboHits: 1,
  comboWindowFrames: 22,
  swordBeam: null,
};

const DEFAULT_SHOT: ShotActionDef = {
  cooldown: SHOT.FIRE_COOLDOWN,
  recovery: MELEE.DURATION,
  ammoMax: SHOT.AMMO_MAX,
  reloadFrames: SHOT.RELOAD_FRAMES,
  projectileCount: 1,
  spreadRadians: 0,
  speed: SHOT.SPEED,
  lifetime: SHOT.LIFETIME,
  homingTurn: SHOT.HOMING_TURN,
  hitRadius: SHOT.HIT_RADIUS,
  muzzleForwardOffset: 30,
  muzzleYOffset: 20,
  damageMultiplier: 1,
  hitstunMultiplier: 1,
  knockbackMultiplier: 1,
  visualKind: "energy",
  chargeable: false,
  chargeTier1Frames: 30,
  chargeTier2Frames: 90,
  chargeTier1DamageMult: 1.6,
  chargeTier2DamageMult: 2.4,
  bulletDrop: 0,
};

const DEFAULT_SPECIAL: SpecialActionDef = {
  cooldown: SPECIAL.COOLDOWN,
  duration: SPECIAL.DURATION,
  radius: SPECIAL.RADIUS,
  damageMultiplier: SPECIAL.DMG_MULT,
  knockbackMultiplier: 1,
};

/**
 * Resolve the TUNED asset-backed action profile for a borg.
 *
 * Source: packages/combat/src/data/actionProfiles.json generated by
 * scripts/gen-combat-action-profiles.mjs from weapon-attachment and action-animation
 * inventories. It is intentionally not labeled DERIVED: hit-bin per-move semantics remain
 * undecoded, so missing data falls back to the old generic constants.
 */
const RESOLVED_CACHE = new WeakMap<BorgProfile, BorgActionProfile>();

export function actionProfileForProfile(profile: BorgProfile): BorgActionProfile {
  const cached = RESOLVED_CACHE.get(profile);
  if (cached) return cached;
  const resolved = resolveActionProfile(profile);
  RESOLVED_CACHE.set(profile, resolved);
  return resolved;
}

function resolveActionProfile(profile: BorgProfile): BorgActionProfile {
  const raw = RAW_PROFILES[profile.id];
  const melee = profile.hasMelee ? { ...DEFAULT_MELEE, ...(raw?.melee ?? {}) } : null;
  const shot = profile.hasShot ? { ...DEFAULT_SHOT, ...(raw?.shot ?? {}) } : null;

  let primary = raw?.primary ?? chooseFallbackPrimary(profile);
  if (primary === "melee" && melee === null && shot !== null) primary = "shot";
  if (primary === "shot" && shot === null && melee !== null) primary = "melee";

  return {
    primary,
    confidence: raw?.confidence ?? "fallback",
    melee,
    shot,
    special: { ...DEFAULT_SPECIAL, ...(raw?.special ?? {}) },
  };
}

export function startingAmmoForProfile(profile: BorgProfile): number {
  return actionProfileForProfile(profile).shot?.ammoMax ?? 0;
}

function chooseFallbackPrimary(profile: BorgProfile): PrimaryAttackKind {
  if (profile.hasShot && !profile.hasMelee) return "shot";
  if (profile.hasMelee && !profile.hasShot) return "melee";
  if (profile.rangePref === "ranged" && profile.hasShot) return "shot";
  return "melee";
}
