import { MELEE, SHOT, SPECIAL } from "./constants.js";
import type { BorgProfile } from "./stats.js";
import type { ProjectileVisualKind } from "./types.js";
import actionProfileData from "./data/actionProfiles.json" with { type: "json" };

export type PrimaryAttackKind = "melee" | "shot";

export interface MeleeActionDef {
  startup: number;
  active: number;
  duration: number;
  cooldown: number;
  range: number;
  yTolerance: number;
  damageMultiplier: number;
  knockbackMultiplier: number;
}

export interface ShotActionDef {
  cooldown: number;
  recovery: number;
  ammoMax: number;
  reloadFrames: number;
  projectileCount: number;
  spreadRadians: number;
  speed: number;
  lifetime: number;
  homingTurn: number;
  hitRadius: number;
  muzzleForwardOffset: number;
  muzzleYOffset: number;
  damageMultiplier: number;
  hitstunMultiplier: number;
  knockbackMultiplier: number;
  visualKind: ProjectileVisualKind;
}

export interface SpecialActionDef {
  cooldown: number;
  duration: number;
  radius: number;
  damageMultiplier: number;
  knockbackMultiplier: number;
}

export interface BorgActionProfile {
  primary: PrimaryAttackKind;
  confidence: "medium" | "low" | "fallback";
  melee: MeleeActionDef | null;
  shot: ShotActionDef | null;
  special: SpecialActionDef;
}

type RawActionProfile = {
  primary?: PrimaryAttackKind;
  confidence?: "medium" | "low" | "fallback";
  melee?: Partial<MeleeActionDef> | null;
  shot?: Partial<ShotActionDef> | null;
  special?: Partial<SpecialActionDef> | null;
};

const RAW_PROFILES = actionProfileData.profiles as Record<string, RawActionProfile>;

const DEFAULT_MELEE: MeleeActionDef = {
  startup: MELEE.STARTUP,
  active: MELEE.ACTIVE,
  duration: MELEE.DURATION,
  cooldown: MELEE.COOLDOWN,
  range: MELEE.RANGE,
  yTolerance: MELEE.Y_TOLERANCE,
  damageMultiplier: 1,
  knockbackMultiplier: 1,
};

const DEFAULT_SHOT: ShotActionDef = {
  cooldown: SHOT.FIRE_COOLDOWN,
  recovery: MELEE.DURATION,
  ammoMax: SHOT.AMMO_MAX,
  reloadFrames: SHOT.RELOAD_FRAMES,
  projectileCount: 1,
  spreadRadians: 0,
  speed: SHOT.SPEED,
  lifetime: SHOT.LIFETIME,
  homingTurn: SHOT.HOMING_TURN,
  hitRadius: SHOT.HIT_RADIUS,
  muzzleForwardOffset: 30,
  muzzleYOffset: 20,
  damageMultiplier: 1,
  hitstunMultiplier: 1,
  knockbackMultiplier: 1,
  visualKind: "energy",
};

const DEFAULT_SPECIAL: SpecialActionDef = {
  cooldown: SPECIAL.COOLDOWN,
  duration: SPECIAL.DURATION,
  radius: SPECIAL.RADIUS,
  damageMultiplier: SPECIAL.DMG_MULT,
  knockbackMultiplier: 1,
};

/**
 * Resolve the TUNED asset-backed action profile for a borg.
 *
 * Source: packages/combat/src/data/actionProfiles.json generated by
 * scripts/gen-combat-action-profiles.mjs from weapon-attachment and action-animation
 * inventories. It is intentionally not labeled DERIVED: hit-bin per-move semantics remain
 * undecoded, so missing data falls back to the old generic constants.
 */
export function actionProfileForProfile(profile: BorgProfile): BorgActionProfile {
  const raw = RAW_PROFILES[profile.id];
  const melee = profile.hasMelee ? { ...DEFAULT_MELEE, ...(raw?.melee ?? {}) } : null;
  const shot = profile.hasShot ? { ...DEFAULT_SHOT, ...(raw?.shot ?? {}) } : null;

  let primary = raw?.primary ?? chooseFallbackPrimary(profile);
  if (primary === "melee" && melee === null && shot !== null) primary = "shot";
  if (primary === "shot" && shot === null && melee !== null) primary = "melee";

  return {
    primary,
    confidence: raw?.confidence ?? "fallback",
    melee,
    shot,
    special: { ...DEFAULT_SPECIAL, ...(raw?.special ?? {}) },
  };
}

export function startingAmmoForProfile(profile: BorgProfile): number {
  return actionProfileForProfile(profile).shot?.ammoMax ?? 0;
}

function chooseFallbackPrimary(profile: BorgProfile): PrimaryAttackKind {
  if (profile.hasShot && !profile.hasMelee) return "shot";
  if (profile.hasMelee && !profile.hasShot) return "melee";
  if (profile.rangePref === "ranged" && profile.hasShot) return "shot";
  return "melee";
}
