// Self-test for ATK-018 (Power Burst fusion pair-data shell).
//
// Verifies research/decomp/data/fusion-pairs-802d352c.json (generated by
// scripts/gen_fusion_pairs.py from behavior-notes.md (aj)) is internally consistent and
// that every referenced spawn id resolves against packages/assets/data/borgs.json.
//
// Deliberately separate from selfcheck.ts (another agent is concurrently editing that
// file) — own entry point, own runner (scripts/run-fusion-tests.mjs), per the
// commandSchema.selftest.ts precedent. Does not import or modify selfcheck.ts/battle.ts.
//
// Run (from repo root), after building packages/combat:
//   node scripts/run-fusion-tests.mjs

import { readFileSync } from "node:fs";
import { dirname, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";

// --- Test scaffolding --------------------------------------------------------------------

let failures = 0;
let checks = 0;

function assertEqual<T>(actual: T, expected: T, label: string): void {
  checks++;
  if (actual !== expected) {
    failures++;
    console.error(`FAIL: ${label} — expected ${String(expected)}, got ${String(actual)}`);
  }
}

function assertTrue(cond: boolean, label: string): void {
  checks++;
  if (!cond) {
    failures++;
    console.error(`FAIL: ${label}`);
  }
}

// --- Data loading --------------------------------------------------------------------------
// Resolve the repo root relative to the COMPILED file (dist/fusionPairs.selftest.js is
// packages/combat/dist/*.js — 3 levels up from repo root), matching the convention already
// used by scripts/*.mjs generators (see scripts/gen-knockback-direction-data.mjs).

const repoRoot = resolvePath(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const fusionPairsPath = resolvePath(repoRoot, "research/decomp/data/fusion-pairs-802d352c.json");
const borgsPath = resolvePath(repoRoot, "packages/assets/data/borgs.json");

interface ResolvedId {
  spawnId: number;
  family: number;
  variant: number;
  plId: string;
  nonRosterResult?: boolean;
}

interface PairEntry {
  partner: ResolvedId;
  result: ResolvedId;
}

interface VariantEntry {
  variant: number;
  listEntryAddr: string;
  subListPtr: string;
  pairCount: number;
  pairs: PairEntry[];
  subListRawHex: string;
}

interface FamilyEntry {
  familyByte: number;
  listPtr: string;
  listWordCount: number;
  nonNullVariantCount: number;
  variants: VariantEntry[];
}

interface FusionPairsDoc {
  provenance: { citation: string; romConstant: string };
  pairTable: {
    addr: string;
    hardBoundCount: number;
    entries: { family: number; addr: string; listPtr: string | null }[];
    emptyFamilies: number[];
    nonNullFamilies: number[];
  };
  rawRegion: { start: string; end: string; hex: string };
  families: Record<string, FamilyEntry>;
  unknownIds: unknown[];
}

function family(doc: FusionPairsDoc, key: "5" | "6"): FamilyEntry {
  const fam = doc.families[key];
  if (!fam) throw new Error(`fusion-pairs JSON missing family ${key}`);
  return fam;
}

function loadJson<T>(p: string): T {
  return JSON.parse(readFileSync(p, "utf8")) as T;
}

/** Parse a big-endian hex string (as emitted by Python `bytes.hex()`) into signed 16-bit
 *  words, avoiding a dependency on the `Buffer` global (not declared in node-shim.d.ts). */
function s16BEFromHex(hex: string, byteOffset: number): number {
  const start = byteOffset * 2;
  const hi = parseInt(hex.slice(start, start + 2), 16);
  const lo = parseInt(hex.slice(start + 2, start + 4), 16);
  const u16 = (hi << 8) | lo;
  return u16 >= 0x8000 ? u16 - 0x10000 : u16;
}

// --- Tests ---------------------------------------------------------------------------------

function testProvenance(doc: FusionPairsDoc): void {
  assertTrue(doc.provenance.citation.includes("(aj)"), "provenance cites behavior-notes (aj)");
  assertEqual(doc.provenance.romConstant, "DAT_802d352c", "provenance names DAT_802d352c");
}

function testPairTableHardBound(doc: FusionPairsDoc): void {
  assertEqual(doc.pairTable.addr, "0x802d352c", "pair table address is 0x802d352c");
  assertEqual(doc.pairTable.hardBoundCount, 17, "pair table hard bound is exactly 17 entries");
  assertEqual(doc.pairTable.entries.length, 17, "pair table dumped exactly 17 entries");
  assertEqual(
    doc.pairTable.entries.map((e) => e.family).join(","),
    Array.from({ length: 17 }, (_, i) => i).join(","),
    "pair table families are exactly 0..16",
  );
}

function testOnlyFamilies5And6NonNull(doc: FusionPairsDoc): void {
  assertEqual(doc.pairTable.nonNullFamilies.join(","), "5,6", "only families 5 and 6 are non-null");
  assertEqual(
    doc.pairTable.emptyFamilies.join(","),
    [0, 1, 2, 3, 4, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16].join(","),
    "all other families (0-4, 7-16) are empty",
  );
  for (const e of doc.pairTable.entries) {
    if (e.family === 5) assertEqual(e.listPtr, "0x802d3420", "family 5 listPtr == 0x802d3420");
    else if (e.family === 6) assertEqual(e.listPtr, "0x802d3480", "family 6 listPtr == 0x802d3480");
    else assertEqual(e.listPtr, null, `family ${e.family} listPtr is null`);
  }
}

function testFamiliesNonEmptyWhereExpected(doc: FusionPairsDoc): void {
  assertTrue(family(doc, "5").nonNullVariantCount > 0, "family 5 has at least one non-null variant");
  assertTrue(family(doc, "6").nonNullVariantCount > 0, "family 6 has at least one non-null variant");
  assertTrue(family(doc, "5").variants.length > 0, "family 5 variants list is non-empty");
  assertTrue(family(doc, "6").variants.length > 0, "family 6 variants list is non-empty");
  for (const fam of Object.values(doc.families)) {
    for (const v of fam.variants) {
      assertTrue(v.pairs.length > 0, `family ${fam.familyByte} variant ${v.variant} has at least one pair`);
      assertEqual(v.pairs.length, v.pairCount, `family ${fam.familyByte} variant ${v.variant} pairCount matches pairs.length`);
    }
  }
}

/** Every sub-list must be terminated by partnerId == -1 — i.e. the extractor stopped because
 *  it found the terminator, not because it hit the safety cap. Re-derived from each
 *  variant's own `subListRawHex` (recorded per-sub-list because family 5's and family 6's
 *  sub-lists live in different, non-adjacent ROM regions — the shared `rawRegion` only
 *  covers the two outer variant-pointer arrays, not the sub-lists themselves). */
function testTerminatorsFromRawHex(doc: FusionPairsDoc): void {
  for (const fam of Object.values(doc.families)) {
    for (const v of fam.variants) {
      const byteLength = v.subListRawHex.length / 2;
      const expectedLength = (v.pairs.length + 1) * 4; // +1 word for the -1 terminator
      assertEqual(
        byteLength,
        expectedLength,
        `family ${fam.familyByte} variant ${v.variant} subListRawHex length matches pairCount+terminator`,
      );
      const terminatorPartner = s16BEFromHex(v.subListRawHex, v.pairs.length * 4);
      assertEqual(
        terminatorPartner,
        -1,
        `family ${fam.familyByte} variant ${v.variant} sub-list terminates with partnerId == -1`,
      );
    }
  }
}

function testAllIdsResolveToRoster(doc: FusionPairsDoc, rosterIds: Set<string>): void {
  assertEqual(doc.unknownIds.length, 0, "no ids were flagged nonRosterResult by the generator");
  let partnerCount = 0;
  let resultCount = 0;
  for (const fam of Object.values(doc.families)) {
    for (const v of fam.variants) {
      for (const pr of v.pairs) {
        partnerCount++;
        resultCount++;
        assertTrue(
          rosterIds.has(pr.partner.plId),
          `partner id ${pr.partner.plId} (spawnId ${pr.partner.spawnId}) resolves to a known roster entry`,
        );
        assertTrue(
          rosterIds.has(pr.result.plId),
          `result id ${pr.result.plId} (spawnId ${pr.result.spawnId}) resolves to a known roster entry`,
        );
        // Cross-check the packing formula itself (family<<8|variant), independent of the
        // generator's own arithmetic, per behavior-notes (n).
        assertEqual(
          pr.partner.plId,
          `pl${pr.partner.family.toString(16).padStart(2, "0")}${pr.partner.variant.toString(16).padStart(2, "0")}`,
          `partner plId matches family<<8|variant packing`,
        );
        assertEqual(
          pr.result.plId,
          `pl${pr.result.family.toString(16).padStart(2, "0")}${pr.result.variant.toString(16).padStart(2, "0")}`,
          `result plId matches family<<8|variant packing`,
        );
      }
    }
  }
  assertTrue(partnerCount > 0, "at least one partner id was checked");
  assertTrue(resultCount > 0, "at least one result id was checked");
}

// --- Runner ---------------------------------------------------------------------------------

export function runSelfTest(): number {
  failures = 0;
  checks = 0;

  const doc = loadJson<FusionPairsDoc>(fusionPairsPath);
  const borgsDoc = loadJson<{ borgs: { id: string }[] }>(borgsPath);
  const rosterIds = new Set(borgsDoc.borgs.map((b) => b.id));

  testProvenance(doc);
  testPairTableHardBound(doc);
  testOnlyFamilies5And6NonNull(doc);
  testFamiliesNonEmptyWhereExpected(doc);
  testTerminatorsFromRawHex(doc);
  testAllIdsResolveToRoster(doc, rosterIds);

  if (failures > 0) {
    console.error(`fusionPairs.selftest: ${failures}/${checks} checks FAILED`);
    return 1;
  }
  console.log(`fusionPairs.selftest: ${checks}/${checks} checks passed`);
  return 0;
}
