// =============================================================================
// inventory.generated.ts — GENERATED by scripts/hle-call-inventory.mjs.
// DO NOT EDIT BY HAND; re-run the script instead.
//
// The measured DVD / disc file access surface of Gotcha Force: every entry point in this
// family that ROM GAME code calls, ranked by static call-site count, plus every
// hardware register in this family's MMIO windows that the corpus touches.
// This is the ranked list the HLE host's work is prioritized by, and the
// denominator its coverage percentage is computed against — so the coverage
// number is DERIVED from a measurement rather than asserted.
//
// SEAM CLASS matters here in a way it did not for GX:
//   "bridged"   — gnt4_*-prefixed, excluded from porting (design V2 F2), so
//                 every call crosses the H2 bridge and needs a host adapter.
//   "in-window" — ordinary ROM code the port compiles into the module. Calls
//                 to it do NOT cross the seam; it is listed because its body
//                 reaches hardware through the MMIO registers below.
//
// HONESTY NOTE (repeated from the generator): these are STATIC counts — how
// many PLACES in the ROM do the thing, not how often it executes. A per-frame
// frequency ranking requires a Dolphin trace and does not exist yet.
//
// Corpus: research/decomp/ghidra-export
// Symbols in the DOL:            47
// Called by game code:           15
// Game call sites:               41
//   of which bridged (seam):     41
//   of which in-window (no seam):0
// MMIO registers touched:        10 (27 reads, 57 writes)
// =============================================================================

export interface HleInventoryEntry {
  /** The C symbol as it appears in the corpus (and as a wasm import name). */
  readonly symbol: string;
  /** The entry point's real GameCube address in this game's DOL. */
  readonly romAddr: number | null;
  /** Whether a call to it crosses the SDK seam at all. */
  readonly seam: "bridged" | "in-window";
  /** Static call sites in ROM game code — the ranking key. */
  readonly gameCalls: number;
  /** Static call sites inside other gnt4_* SDK/HSD functions (context only). */
  readonly sdkInternalCalls: number;
  /** Distinct ROM functions that call it. */
  readonly distinctGameCallers: number;
}

export interface HleMmioEntry {
  /** The memory-mapped register address. */
  readonly register: number;
  /** Which hardware block it belongs to. */
  readonly window: string;
  /** Static lines that read it. */
  readonly reads: number;
  /** Static lines that write it. */
  readonly writes: number;
  /** Distinct ROM functions that touch it. */
  readonly functions: number;
}

/** DVD / disc file access entry points called by ROM game code, ranked by static call sites. */
export const DVD_CALL_INVENTORY: readonly HleInventoryEntry[] = [
  { symbol: "gnt4_DVDGetCommandBlockStatus_bl", romAddr: 0x8020f7d0, seam: "bridged", gameCalls: 11, sdkInternalCalls: 0, distinctGameCallers: 5 },
  { symbol: "gnt4_DVDGetDriveStatus_bl", romAddr: 0x8020f81c, seam: "bridged", gameCalls: 7, sdkInternalCalls: 1, distinctGameCallers: 5 },
  { symbol: "gnt4_DVDCheckDisk_bl", romAddr: 0x8020fc7c, seam: "bridged", gameCalls: 5, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_DVDInit_bl", romAddr: 0x8020d798, seam: "bridged", gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 3 },
  { symbol: "gnt4_DVDCancel_bl", romAddr: 0x8020fba4, seam: "bridged", gameCalls: 2, sdkInternalCalls: 1, distinctGameCallers: 2 },
  { symbol: "gnt4_DVDClose_bl", romAddr: 0x8020d2b4, seam: "bridged", gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_DVDOpen_bl", romAddr: 0x8020d1ec, seam: "bridged", gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_DVDReadAbsAsyncPrio_bl", romAddr: 0x8020f380, seam: "bridged", gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_DVDGetCurrentDiskID_bl", romAddr: 0x8020fc74, seam: "bridged", gameCalls: 1, sdkInternalCalls: 1, distinctGameCallers: 1 },
  { symbol: "gnt4___DVDPrepareResetAsync_bl", romAddr: 0x8020fd74, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_DVDInquiryAsync_bl", romAddr: 0x8020f6bc, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_DVDReadPrio_bl", romAddr: 0x8020d5ec, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_DVDResume_bl", romAddr: 0x8020f8d8, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_DVDSetAutoInvalidation", romAddr: 0x8020f8c8, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_HSD_DVDInit", romAddr: 0x80253bbc, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
];

/** Hardware registers in this family's MMIO windows that the corpus touches. */
export const DVD_MMIO_INVENTORY: readonly HleMmioEntry[] = [
  { register: 0xcc006004, window: "DI", reads: 17, writes: 21, functions: 9 },
  { register: 0xcc006008, window: "DI", reads: 0, writes: 9, functions: 9 },
  { register: 0xcc00601c, window: "DI", reads: 0, writes: 9, functions: 9 },
  { register: 0xcc006018, window: "DI", reads: 2, writes: 4, functions: 6 },
  { register: 0xcc006020, window: "DI", reads: 5, writes: 0, functions: 3 },
  { register: 0xcc006000, window: "DI", reads: 1, writes: 3, functions: 3 },
  { register: 0xcc00600c, window: "DI", reads: 0, writes: 4, functions: 4 },
  { register: 0xcc006010, window: "DI", reads: 0, writes: 4, functions: 4 },
  { register: 0xcc006014, window: "DI", reads: 1, writes: 3, functions: 4 },
  { register: 0xcc006024, window: "DI", reads: 1, writes: 0, functions: 1 },
];

/** Total static game-code call sites across the whole ranked surface.
 *  Widened to `number` deliberately: a literal type here would make the
 *  divide-by-zero guard below a compile error rather than a guard. */
export const DVD_GAME_CALL_SITES: number = 41;

/** Static game-code call sites that actually CROSS the seam (gnt4_* callees). */
export const DVD_BRIDGED_GAME_CALL_SITES: number = 41;

/** Look one entry point up by symbol. */
export function dvdInventoryEntry(symbol: string): HleInventoryEntry | undefined {
  return DVD_CALL_INVENTORY.find((e) => e.symbol === symbol);
}

/**
 * Coverage of the ranked surface, by BOTH measures that matter: how many
 * distinct entry points are implemented, and what share of the ROM's static
 * call sites they account for (weighted coverage). Reporting only the first
 * understates a steep distribution; reporting only the second hides a long
 * unimplemented tail. The host reports both, always together.
 */
export function dvdCoverage(implemented: Iterable<string>): {
  implementedSymbols: number;
  totalSymbols: number;
  symbolPct: number;
  coveredCallSites: number;
  totalCallSites: number;
  callSitePct: number;
} {
  const set = new Set(implemented);
  const covered = DVD_CALL_INVENTORY.filter((e) => set.has(e.symbol));
  const coveredCallSites = covered.reduce((sum, e) => sum + e.gameCalls, 0);
  const totalSymbols = DVD_CALL_INVENTORY.length;
  return {
    implementedSymbols: covered.length,
    totalSymbols,
    symbolPct: totalSymbols === 0 ? 0 : Math.round((covered.length / totalSymbols) * 1000) / 10,
    coveredCallSites,
    totalCallSites: DVD_GAME_CALL_SITES,
    callSitePct:
      DVD_GAME_CALL_SITES === 0 ? 0 : Math.round((coveredCallSites / DVD_GAME_CALL_SITES) * 1000) / 10,
  };
}
