/* gf_dispatch_companion.c -- address-keyed uniform-ABI dispatch
 * (docs/playable-port-design.md V4 H3).
 *
 * AUTO-GENERATED by the assembly gate (src/port_dispatch_companion.py)
 * for one N-unit window. DERIVED artifact: never hand-edited,
 * regenerated on every window link.
 *
 * One adapter thunk per function DEFINED in the window, all sharing
 * the canonical signature (i32 argptr) -> i32; the table maps GC code
 * address -> thunk; a lookup miss calls the declared host import
 * __gf_dispatch_miss (the H2/H3 bridge hook + bridged-call ledger),
 * never traps.
 */
#include "gf_dispatch_frame.h"

/* True callees, declared by wasm value class (see companion module
 * docstring): identical object-level wasm signatures by construction. */
extern void FUN_80079978(int);
extern void FUN_800799ac(int);
extern void FUN_800799cc(int);
extern void FUN_800799ec(int, int);
extern void FUN_80079a40(int);
extern void FUN_80079a7c(int);
extern void FUN_80079ab8(int);
extern void FUN_80079b08(int);

/* Host bridge hook (H3): unknown gc_addr routes here and is ledgered
 * host-side. The wasm side only DECLARES it; a miss is a bridge call,
 * never a trap. */
extern int __gf_dispatch_miss(unsigned int gc_addr, int argptr);

/* FUN_80079978 @ 0x80079978 (marker): void(i32) */
static int __gf_thunk_80079978(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_80079978(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_800799ac @ 0x800799ac (marker): void(i32) */
static int __gf_thunk_800799ac(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_800799ac(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_800799cc @ 0x800799cc (marker): void(i32) */
static int __gf_thunk_800799cc(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_800799cc(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_800799ec @ 0x800799ec (marker): void(i32, i32) */
static int __gf_thunk_800799ec(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_800799ec(frame->args[0].i32, frame->args[1].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_80079a40 @ 0x80079a40 (marker): void(i32) */
static int __gf_thunk_80079a40(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_80079a40(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_80079a7c @ 0x80079a7c (marker): void(i32) */
static int __gf_thunk_80079a7c(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_80079a7c(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_80079ab8 @ 0x80079ab8 (marker): void(i32) */
static int __gf_thunk_80079ab8(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_80079ab8(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* FUN_80079b08 @ 0x80079b08 (marker): void(i32) */
static int __gf_thunk_80079b08(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  FUN_80079b08(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* Arity ledger: a caller whose arg_count differs from the callee's
 * known arity still DISPATCHES (the register-residue class is
 * legitimate, V5 note 1) but the event is counted here for the host
 * to read. Ledger data only -- never a gate, never a trap. */
static unsigned int __gf_arity_mismatch_count = 0u;

unsigned int __gf_dispatch_arity_mismatches(void) {
  return __gf_arity_mismatch_count;
}

typedef int (*__gf_thunk_fn)(int argptr);

static const unsigned int __gf_dispatch_addrs[8] = {
  0x80079978u,
  0x800799acu,
  0x800799ccu,
  0x800799ecu,
  0x80079a40u,
  0x80079a7cu,
  0x80079ab8u,
  0x80079b08u,
};

static const __gf_thunk_fn __gf_dispatch_thunks[8] = {
  __gf_thunk_80079978,
  __gf_thunk_800799ac,
  __gf_thunk_800799cc,
  __gf_thunk_800799ec,
  __gf_thunk_80079a40,
  __gf_thunk_80079a7c,
  __gf_thunk_80079ab8,
  __gf_thunk_80079b08,
};

static const unsigned char __gf_dispatch_arity[8] = {
  1u, /* FUN_80079978 */
  1u, /* FUN_800799ac */
  1u, /* FUN_800799cc */
  2u, /* FUN_800799ec */
  1u, /* FUN_80079a40 */
  1u, /* FUN_80079a7c */
  1u, /* FUN_80079ab8 */
  1u, /* FUN_80079b08 */
};

int __gf_dispatch(unsigned int gc_addr, int argptr) {
  unsigned int lo = 0;
  unsigned int hi = 8u;
  while (lo < hi) {
    unsigned int mid = lo + (hi - lo) / 2u;
    unsigned int probe = __gf_dispatch_addrs[mid];
    if (probe == gc_addr) {
      const __gf_dispatch_frame *frame =
          (const __gf_dispatch_frame *)argptr;
      if (frame->arg_count != __gf_dispatch_arity[mid]) {
        __gf_arity_mismatch_count += 1u;
      }
      return __gf_dispatch_thunks[mid](argptr);
    }
    if (probe < gc_addr) {
      lo = mid + 1u;
    } else {
      hi = mid;
    }
  }
  return __gf_dispatch_miss(gc_addr, argptr);
}

/* Outbound entry for the ROM's own lowered `bctrl` call sites
 * (src/port_indirect_lowering.py). Same table, same miss import, plus
 * the originating SITE and the per-argument class array. */
extern void __gf_dispatch_enter(unsigned int site, unsigned int gc_addr,
                                 int argptr, int classptr, int resolved);
extern void __gf_dispatch_exit(unsigned int site, unsigned int gc_addr,
                                int argptr, int resolved, int result);
static int __gf_dispatch_index(unsigned int gc_addr) {
  unsigned int lo = 0;
  unsigned int hi = 8u;
  while (lo < hi) {
    unsigned int mid = lo + (hi - lo) / 2u;
    unsigned int probe = __gf_dispatch_addrs[mid];
    if (probe == gc_addr) { return (int)mid; }
    if (probe < gc_addr) { lo = mid + 1u; } else { hi = mid; }
  }
  return -1;
}
int __gf_dispatch_at(unsigned int site, unsigned int gc_addr, int argptr,
                        int classptr) {
  int idx = __gf_dispatch_index(gc_addr);
  int result;
  __gf_dispatch_enter(site, gc_addr, argptr, classptr, idx >= 0);
  if (idx >= 0) {
    const __gf_dispatch_frame *frame =
        (const __gf_dispatch_frame *)argptr;
    if (frame->arg_count != __gf_dispatch_arity[idx]) {
      __gf_arity_mismatch_count += 1u;
    }
    result = __gf_dispatch_thunks[idx](argptr);
  } else {
    result = __gf_dispatch_miss(gc_addr, argptr);
  }
  __gf_dispatch_exit(site, gc_addr, argptr, idx >= 0, result);
  return result;
}
