/* gf_indirect_lowering.h -- GF outbound indirect-call lowering, version 1.
 *
 * AUTO-GENERATED by the assembly gate (src/port_indirect_lowering.py).
 * DERIVED artifact: never hand-edited, regenerated on every window link.
 *
 * The ROM's `(*(code *)addr)(args)` becomes, textually:
 *
 *   do {
 *     __gf_indirect_call __gf_c;
 *     __gf_indirect_begin(&__gf_c);
 *     __GF_ARG(__gf_c, 0, <arg0>);
 *     __GF_ARG(__gf_c, 1, <arg1>);
 *     __gf_c.frame.arg_count = 2u;
 *     __gf_dispatch_at(<site>, (unsigned int)(<target>),
 *                      __GF_ADDR(&__gf_c.frame), __GF_ADDR(__gf_c.classes));
 *   } while (0);
 *
 * WHY A PER-CALL LOCAL FRAME. The frame lives on the C stack, so it is at a
 * real linear-memory address, it is reentrancy- and recursion-safe, and it
 * costs no allocator. Its address is what the uniform ABI calls `argptr`.
 *
 * WHY `_Generic`. The frame's slots are class-tagged (i32/i64/f32/f64) and a
 * decompiled call site gives no prototype for its callee, so the ONLY
 * authority for an argument's class is the STATIC TYPE OF THE ARGUMENT
 * EXPRESSION ITSELF. `_Generic` reads exactly that, at compile time, from the
 * expression the ROM's own C hands the call. Nothing is guessed and nothing is
 * hand-listed. The class is ALSO written into a parallel `classes` array so
 * the host observing the dispatch can read each slot at the width the module
 * wrote it -- the observer never has to assume a signature.
 *
 * Sub-i32 integers reach the slot CALLER-EXTENDED, which is the frame ABI's
 * stated argument convention: the usual arithmetic conversions promote a
 * `char`/`short`/`unsigned char` argument to `int`/`unsigned int` at the call,
 * and `__gf_arg_w` stores that already-extended 32-bit value.
 *
 * Pointers take the `default` branch and convert to `unsigned int`. That is
 * the design's pointer marshalling (a 32-bit linear-memory address) and it
 * relies on `-Wno-int-conversion`, which the unit and window builds both pass.
 */
#ifndef GF_INDIRECT_LOWERING_H
#define GF_INDIRECT_LOWERING_H

#include "gf_dispatch_frame.h"

#define GF_INDIRECT_LOWERING_VERSION 1

/* The companion's site-tagged dispatch entry. `classptr` is the address of the
 * per-call class array; the companion passes both straight through to the
 * observation imports in trace mode and ignores them otherwise. */
extern int __gf_dispatch_at(unsigned int site, unsigned int gc_addr, int argptr,
                            int classptr);

typedef struct __gf_indirect_call {
  __gf_dispatch_frame frame;
  unsigned char classes[GF_DISPATCH_MAX_ARGS];
} __gf_indirect_call;

static void __gf_indirect_begin(__gf_indirect_call *c) {
  unsigned int i = 0u;
  c->frame.arg_count = 0u;
  c->frame.ret_class = GF_DISPATCH_CLASS_VOID;
  c->frame.ret.i64 = 0;
  for (i = 0u; i < (unsigned int)GF_DISPATCH_MAX_ARGS; ++i) {
    c->frame.args[i].i64 = 0;
    c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_VOID;
  }
}

/* One setter per wasm value class. `_Generic` selects the FUNCTION, and the
 * call is type-checked only against the selected one -- the unselected
 * associations are function designators and are always well formed. */
static void __gf_arg_w(__gf_indirect_call *c, unsigned int i, unsigned int v) {
  c->frame.args[i].i64 = 0;
  c->frame.args[i].u32 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_I32;
}
static void __gf_arg_i64(__gf_indirect_call *c, unsigned int i, long long v) {
  c->frame.args[i].i64 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_I64;
}
static void __gf_arg_u64(__gf_indirect_call *c, unsigned int i,
                         unsigned long long v) {
  c->frame.args[i].u64 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_I64;
}
static void __gf_arg_f32(__gf_indirect_call *c, unsigned int i, float v) {
  c->frame.args[i].i64 = 0;
  c->frame.args[i].f32 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_F32;
}
static void __gf_arg_f64(__gf_indirect_call *c, unsigned int i, double v) {
  c->frame.args[i].f64 = v;
  c->classes[i] = (unsigned char)GF_DISPATCH_CLASS_F64;
}

#define __GF_ARG(c, i, v)                                                     \
  _Generic((v),                                                               \
           float: __gf_arg_f32,                                               \
           double: __gf_arg_f64,                                              \
           long long: __gf_arg_i64,                                           \
           unsigned long long: __gf_arg_u64,                                  \
           default: __gf_arg_w)(&(c), (unsigned int)(i), (v))

/* A linear-memory address as the uniform ABI's i32. */
#define __GF_ADDR(p) ((int)(unsigned int)(unsigned long)(p))

/* Read the pointer a `(**(code **)E)(...)` site dereferences. E is a GC
 * address in linear memory holding the callee's code address. */
#define __GF_DEREF(e) (*(unsigned int *)(unsigned int)(e))

#endif /* GF_INDIRECT_LOWERING_H */
