/* gf_dispatch_companion.c -- address-keyed uniform-ABI dispatch
 * (docs/playable-port-design.md V4 H3).
 *
 * AUTO-GENERATED by the assembly gate (src/port_dispatch_companion.py)
 * for one N-unit window. DERIVED artifact: never hand-edited,
 * regenerated on every window link.
 *
 * One adapter thunk per function DEFINED in the window, all sharing
 * the canonical signature (i32 argptr) -> i32; the table maps GC code
 * address -> thunk; a lookup miss calls the declared host import
 * __gf_dispatch_miss (the H2/H3 bridge hook + bridged-call ledger),
 * never traps.
 */
#include "gf_dispatch_frame.h"

/* True callees, declared by wasm value class (see companion module
 * docstring): identical object-level wasm signatures by construction. */
extern void zz_01a2cfc_(int);
extern void zz_01a2d4c_(int);
extern void zz_01a2e08_(int);
extern void zz_01a2ebc_(int);
extern void zz_01a30fc_(int);
extern void zz_01a31a0_(int);
extern void zz_01a31d8_(int);
extern void zz_01a324c_(long long, double, double, int);

/* Host bridge hook (H3): unknown gc_addr routes here and is ledgered
 * host-side. The wasm side only DECLARES it; a miss is a bridge call,
 * never a trap. */
extern int __gf_dispatch_miss(unsigned int gc_addr, int argptr);

/* zz_01a2cfc_ @ 0x801a2cfc (marker): void(i32) */
static int __gf_thunk_801a2cfc(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a2cfc_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a2d4c_ @ 0x801a2d4c (marker): void(i32) */
static int __gf_thunk_801a2d4c(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a2d4c_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a2e08_ @ 0x801a2e08 (marker): void(i32) */
static int __gf_thunk_801a2e08(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a2e08_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a2ebc_ @ 0x801a2ebc (marker): void(i32) */
static int __gf_thunk_801a2ebc(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a2ebc_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a30fc_ @ 0x801a30fc (marker): void(i32) */
static int __gf_thunk_801a30fc(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a30fc_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a31a0_ @ 0x801a31a0 (marker): void(i32) */
static int __gf_thunk_801a31a0(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a31a0_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a31d8_ @ 0x801a31d8 (marker): void(i32) */
static int __gf_thunk_801a31d8(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a31d8_(frame->args[0].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* zz_01a324c_ @ 0x801a324c (marker): void(i64, f64, f64, i32) */
static int __gf_thunk_801a324c(int argptr) {
  __gf_dispatch_frame *frame = (__gf_dispatch_frame *)argptr;
  zz_01a324c_(frame->args[0].i64, frame->args[1].f64, frame->args[2].f64, frame->args[3].i32);
  frame->ret_class = GF_DISPATCH_CLASS_VOID;
  frame->ret.i64 = 0;
  return 0;
}

/* Arity ledger: a caller whose arg_count differs from the callee's
 * known arity still DISPATCHES (the register-residue class is
 * legitimate, V5 note 1) but the event is counted here for the host
 * to read. Ledger data only -- never a gate, never a trap. */
static unsigned int __gf_arity_mismatch_count = 0u;

unsigned int __gf_dispatch_arity_mismatches(void) {
  return __gf_arity_mismatch_count;
}

typedef int (*__gf_thunk_fn)(int argptr);

static const unsigned int __gf_dispatch_addrs[8] = {
  0x801a2cfcu,
  0x801a2d4cu,
  0x801a2e08u,
  0x801a2ebcu,
  0x801a30fcu,
  0x801a31a0u,
  0x801a31d8u,
  0x801a324cu,
};

static const __gf_thunk_fn __gf_dispatch_thunks[8] = {
  __gf_thunk_801a2cfc,
  __gf_thunk_801a2d4c,
  __gf_thunk_801a2e08,
  __gf_thunk_801a2ebc,
  __gf_thunk_801a30fc,
  __gf_thunk_801a31a0,
  __gf_thunk_801a31d8,
  __gf_thunk_801a324c,
};

static const unsigned char __gf_dispatch_arity[8] = {
  1u, /* zz_01a2cfc_ */
  1u, /* zz_01a2d4c_ */
  1u, /* zz_01a2e08_ */
  1u, /* zz_01a2ebc_ */
  1u, /* zz_01a30fc_ */
  1u, /* zz_01a31a0_ */
  1u, /* zz_01a31d8_ */
  4u, /* zz_01a324c_ */
};

int __gf_dispatch(unsigned int gc_addr, int argptr) {
  unsigned int lo = 0;
  unsigned int hi = 8u;
  while (lo < hi) {
    unsigned int mid = lo + (hi - lo) / 2u;
    unsigned int probe = __gf_dispatch_addrs[mid];
    if (probe == gc_addr) {
      const __gf_dispatch_frame *frame =
          (const __gf_dispatch_frame *)argptr;
      if (frame->arg_count != __gf_dispatch_arity[mid]) {
        __gf_arity_mismatch_count += 1u;
      }
      return __gf_dispatch_thunks[mid](argptr);
    }
    if (probe < gc_addr) {
      lo = mid + 1u;
    } else {
      hi = mid;
    }
  }
  return __gf_dispatch_miss(gc_addr, argptr);
}

/* Outbound entry for the ROM's own lowered `bctrl` call sites
 * (src/port_indirect_lowering.py). Same table, same miss import, plus
 * the originating SITE and the per-argument class array. */
extern void __gf_dispatch_enter(unsigned int site, unsigned int gc_addr,
                                 int argptr, int classptr, int resolved);
extern void __gf_dispatch_exit(unsigned int site, unsigned int gc_addr,
                                int argptr, int resolved, int result);
static int __gf_dispatch_index(unsigned int gc_addr) {
  unsigned int lo = 0;
  unsigned int hi = 8u;
  while (lo < hi) {
    unsigned int mid = lo + (hi - lo) / 2u;
    unsigned int probe = __gf_dispatch_addrs[mid];
    if (probe == gc_addr) { return (int)mid; }
    if (probe < gc_addr) { lo = mid + 1u; } else { hi = mid; }
  }
  return -1;
}
int __gf_dispatch_at(unsigned int site, unsigned int gc_addr, int argptr,
                        int classptr) {
  int idx = __gf_dispatch_index(gc_addr);
  int result;
  __gf_dispatch_enter(site, gc_addr, argptr, classptr, idx >= 0);
  if (idx >= 0) {
    const __gf_dispatch_frame *frame =
        (const __gf_dispatch_frame *)argptr;
    if (frame->arg_count != __gf_dispatch_arity[idx]) {
      __gf_arity_mismatch_count += 1u;
    }
    result = __gf_dispatch_thunks[idx](argptr);
  } else {
    result = __gf_dispatch_miss(gc_addr, argptr);
  }
  __gf_dispatch_exit(site, gc_addr, argptr, idx >= 0, result);
  return result;
}
