/* gf_dispatch_frame.h -- GF uniform dispatch frame ABI, version 1.
 *
 * AUTO-GENERATED by the assembly gate (src/port_dispatch_companion.py).
 * DERIVED artifact: never hand-edited, regenerated on every window link.
 *
 * Design contract (docs/playable-port-design.md V4 H3): every entry in the
 * address-keyed function table is an adapter thunk with ONE canonical wasm
 * signature, (i32 argptr) -> i32. `argptr` is the byte address, in the shared
 * linear memory, of one __gf_dispatch_frame. The thunk unmarshals the frame
 * into the callee's true parameters, calls the callee directly, and marshals
 * the return back into the frame.
 *
 * Frame layout (fixed, little-endian wasm32 linear memory):
 *
 *   offset 0x00  u32 arg_count   caller-written: how many arg slots the CALL
 *                                SITE populated. Informational/ledger data
 *                                only -- thunks never gate on it, because PPC
 *                                indirect calls are signature-agnostic and a
 *                                cross-class caller legitimately writes fewer
 *                                slots than the callee reads (the register-
 *                                residue class, V5 note 1).
 *   offset 0x04  u32 ret_class   thunk-written: GF_DISPATCH_CLASS_* of the
 *                                value in the return slot (VOID => slot 0).
 *   offset 0x08  slot ret        thunk-written return slot (8 bytes).
 *   offset 0x10  slot args[16]   caller-written argument slots, one 8-byte
 *                                slot per argument, in callee parameter
 *                                order. i32/f32 occupy the LOW 4 bytes of
 *                                their slot; i64/f64 occupy all 8.
 *
 *   sizeof(frame) == 0x90, alignment 8.
 *
 * Return convention: the thunk's i32 result is the i32 VIEW of the return
 * value (the value itself for i32 returns, the LOW 32 bits for i64, 0 for
 * f32/f64/void). NOTE the deliberate asymmetry with the source ABI: PPC32
 * EABI returns an i64 in r3:r4 with r3 carrying the HIGH word, so for i64
 * returns the thunk's i32 result is NOT an r3 image. Consumers MUST read
 * the full 8-byte ret slot (+0x08) for i64/f32/f64 returns; the frame's
 * ret slot + ret_class are the authoritative, full-width return channel,
 * and the i32 result is a convenience view only.
 *
 * Argument convention: sub-i32 integer arguments (char/short) are supplied
 * PPC-register-width pre-extended by the CALLER (caller-extends): the call
 * site writes the already sign-/zero-extended 32-bit value into the low 4
 * bytes of the slot, and thunks pass it through without re-extending.
 *
 * Pointer parameters and returns marshal as i32 (a 32-bit linear-memory
 * address); see dispatch_value_class in src/port_assembly_abi.py.
 */
#ifndef GF_DISPATCH_FRAME_H
#define GF_DISPATCH_FRAME_H

#include <stddef.h>

#define GF_DISPATCH_FRAME_VERSION 1
#define GF_DISPATCH_MAX_ARGS 16

#define GF_DISPATCH_CLASS_VOID 0
#define GF_DISPATCH_CLASS_I32 1
#define GF_DISPATCH_CLASS_I64 2
#define GF_DISPATCH_CLASS_F32 3
#define GF_DISPATCH_CLASS_F64 4

typedef union __gf_dispatch_slot {
  int i32;
  unsigned int u32;
  long long i64;
  unsigned long long u64;
  float f32;
  double f64;
  unsigned char raw[8];
} __gf_dispatch_slot;

typedef struct __gf_dispatch_frame {
  unsigned int arg_count; /* +0x00 */
  unsigned int ret_class; /* +0x04 */
  __gf_dispatch_slot ret; /* +0x08 */
  __gf_dispatch_slot args[GF_DISPATCH_MAX_ARGS]; /* +0x10 */
} __gf_dispatch_frame;

_Static_assert(sizeof(__gf_dispatch_slot) == 8, "gf dispatch slot is 8 bytes");
_Static_assert(offsetof(__gf_dispatch_frame, ret_class) == 0x04,
               "gf dispatch ret_class at +0x04");
_Static_assert(offsetof(__gf_dispatch_frame, ret) == 0x08,
               "gf dispatch return slot at +0x08");
_Static_assert(offsetof(__gf_dispatch_frame, args) == 0x10,
               "gf dispatch arg slots at +0x10");
_Static_assert(sizeof(__gf_dispatch_frame) == 0x90,
               "gf dispatch frame is 0x90 bytes");

#endif /* GF_DISPATCH_FRAME_H */
