// Generated by scripts/build-stage-catalog-module.mjs from apps/game/public/stages/manifest.json.
// Do not hand-edit. Rerun `npm run manifest:stage-catalog` after stage exports change.

export type StageCatalogEntry = {
  id: string;
  status: string;
  modelCount: number;
  renderStatus: string;
  visualComplete: boolean;
  collisionCount: number;
  setArcCount: number;
};

export const EXPORTED_STAGE_CATALOG = [
  {
    "id": "st00",
    "status": "verified-visual-and-collision",
    "modelCount": 40,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st01",
    "status": "verified-visual-and-collision",
    "modelCount": 78,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st02",
    "status": "verified-visual-and-collision",
    "modelCount": 51,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st03",
    "status": "verified-visual-and-collision",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st04",
    "status": "verified-visual-and-collision",
    "modelCount": 52,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st05",
    "status": "verified-visual-and-collision",
    "modelCount": 28,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st06",
    "status": "verified-visual-and-collision",
    "modelCount": 4,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st07",
    "status": "verified-visual-and-collision",
    "modelCount": 4,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st08",
    "status": "verified-visual-and-collision",
    "modelCount": 52,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st09",
    "status": "verified-visual-and-collision",
    "modelCount": 9,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 1
  },
  {
    "id": "st0a",
    "status": "verified-visual-and-collision",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st0b",
    "status": "verified-visual-and-collision",
    "modelCount": 28,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st0c",
    "status": "verified-visual-and-collision",
    "modelCount": 20,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st0d",
    "status": "verified-visual-and-collision",
    "modelCount": 17,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st0e",
    "status": "verified-visual-and-collision",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st0f",
    "status": "verified-visual-and-collision",
    "modelCount": 13,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 4
  },
  {
    "id": "st10",
    "status": "verified-visual-and-collision",
    "modelCount": 7,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 0
  },
  {
    "id": "st20",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 40,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st21",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 78,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st22",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 51,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st23",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st24",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 52,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st25",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 28,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st29",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 9,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st2a",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st2b",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 28,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st2c",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 20,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st2e",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st40",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 40,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st41",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 78,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st42",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 51,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st43",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st44",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 52,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st45",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 28,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st49",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 9,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st4a",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st4b",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 28,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st4c",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 20,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "st4e",
    "status": "visual-exported-no-source-hit-files",
    "modelCount": 43,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 0,
    "setArcCount": 0
  },
  {
    "id": "stff",
    "status": "verified-visual-and-collision",
    "modelCount": 83,
    "renderStatus": "glb-complete",
    "visualComplete": true,
    "collisionCount": 3,
    "setArcCount": 0
  }
] as const satisfies readonly StageCatalogEntry[];

export type ExportedStageId = (typeof EXPORTED_STAGE_CATALOG)[number]["id"];

export const EXPORTED_STAGE_IDS = EXPORTED_STAGE_CATALOG.map((stage) => stage.id) as readonly ExportedStageId[];

export const DEFAULT_ARENA_STAGE: ExportedStageId = "st00";

const EXPORTED_STAGE_ID_SET = new Set<string>(EXPORTED_STAGE_IDS);

export function isExportedStageId(value: string): value is ExportedStageId {
  return EXPORTED_STAGE_ID_SET.has(value);
}

export function stageCatalogEntry(id: string): StageCatalogEntry | null {
  return EXPORTED_STAGE_CATALOG.find((stage) => stage.id === id) ?? null;
}
