/* gf_gx_wgpipe.h -- GameCube write-gather-pipe lowering, ABI version 1.
 *
 * AUTO-GENERATED by the assembly gate (src/port_wgpipe_lowering.py).
 * DERIVED artifact: never hand-edited, regenerated on every window link.
 *
 * WHY THIS EXISTS. The ROM submits vertices by storing them to the memory-
 * mapped write-gather pipe at 0xCC008000, not by calling a function (1143
 * such stores in the decompiled export; the SDK's GXEnd is an empty macro, so
 * primitives end on vertex count). The composed module's linear memory is
 * 0x807A0000 bytes, so a literal store to 0xCC008000 is out of bounds and
 * traps. The gate rewrites each store into one of the calls below, which the
 * browser HLE host services with its FIFO decoder
 * (packages/rom-runtime/src/gx/fifo.ts).
 *
 * THE CONTRACT. Each import receives ONE store's VALUE, at the store's
 * WIDTH, in program order. The host does the serialization, and it is
 * BIG-endian: the FIFO carries console register-order bytes, unlike the
 * little-endian linear memory the rest of the runtime uses. So u16 0x0280
 * reaches the wire as 02 80, and f32 1.0f as 3f 80 00 00.
 *
 * WIDTH is carried by the macro the gate chose, which comes from the Ghidra
 * field spelling -- the decompiler's record of the store instruction's width.
 *
 * FLOATNESS is decided HERE, by the C type system, not by the rewriter
 * looking at the text. A 32-bit store of a float must put the f32 bit
 * pattern on the wire (`stfs`), while a 32-bit store of an integer must put
 * the integer there; the two are different bytes for the same numeric value.
 * `_Generic` routes on the static type of the stored expression, so a bare
 * `DAT_cc008000 = fVar1;` with no cast in the text still reaches the f32
 * import. The routing table is proved below by _Static_assert, so a compiler
 * that disagreed with this comment would fail the build rather than draw a
 * wrong frame.
 *
 * NARROW STORES (8/16-bit) route unconditionally through the integer
 * imports. That is not an assumption about the corpus: `DAT_cc008000._0_1_ =
 * v` in C means "convert v to a 1-byte object", and `(unsigned int)(v) &
 * 0xff` is that conversion for every scalar type v can have, floating-point
 * included. (Measured: zero narrow stores in the export have a floating-point
 * right-hand side.)
 */
#ifndef GF_GX_WGPIPE_H
#define GF_GX_WGPIPE_H

#define GF_WGPIPE_ABI_VERSION 1

/* The pipe window, for the record and for the assertions below. */
#define GF_WGPIPE_BASE 0xCC008000u
#define GF_WGPIPE_LIMIT 0xCC008020u

/* The host imports. Names are the HOST's (packages/rom-runtime/src/gx/
 * adapters.ts, WGPIPE_SYMBOLS) and are matched exactly. */
extern void __gf_gx_wgpipe_u8(unsigned int value);
extern void __gf_gx_wgpipe_u16(unsigned int value);
extern void __gf_gx_wgpipe_u32(unsigned int value);
extern void __gf_gx_wgpipe_f32(float value);

/* Static routing predicate: 1 for a floating-point stored expression, 0
 * otherwise. The controlling expression of _Generic is never evaluated, so
 * this costs nothing and has no side effects. */
#define GF_WGPIPE_IS_FP(v) \
    _Generic((v), float: 1, double: 1, long double: 1, default: 0)

/* The two conversions. Exactly one is ever evaluated (the untaken arm of the
 * conditional below is not evaluated, and _Generic never evaluates an
 * unselected association), so a stored expression with side effects is
 * evaluated exactly once -- same as the assignment it replaces. Every
 * association type-checks for every scalar type, which is why the unselected
 * ones are harmless: (unsigned int)(v) is a legal explicit cast from a
 * pointer or a float, and (float)(v) is legal from any arithmetic type. */
#define GF_WGPIPE_AS_F32(v) \
    _Generic((v), \
             float: (float)(v), \
             double: (float)(v), \
             long double: (float)(v), \
             default: 0.0f)
#define GF_WGPIPE_AS_U32(v) \
    _Generic((v), \
             float: 0u, \
             double: 0u, \
             long double: 0u, \
             default: (unsigned int)(v))

/* One pipe store, at each width. GF_WGPIPE_IS_FP folds at compile time, so
 * the 32-bit form is a single direct call in the generated code. */
#define GF_WGPIPE_W32(v) \
    (GF_WGPIPE_IS_FP(v) ? __gf_gx_wgpipe_f32(GF_WGPIPE_AS_F32(v)) \
                        : __gf_gx_wgpipe_u32(GF_WGPIPE_AS_U32(v)))
#define GF_WGPIPE_W16(v) __gf_gx_wgpipe_u16((unsigned int)(v) & 0xffffu)
#define GF_WGPIPE_W8(v)  __gf_gx_wgpipe_u8((unsigned int)(v) & 0xffu)

/* --- compiler-proved invariants ------------------------------------------
 * These are the claims the lowering rests on. If the toolchain ever
 * disagrees with one, the window fails to compile instead of drawing a
 * wrong frame. */
_Static_assert(GF_WGPIPE_LIMIT - GF_WGPIPE_BASE == 32u,
               "the write-gather pipe is a 32-byte window");
_Static_assert(sizeof(float) == 4,
               "a 32-bit pipe store of a float must be exactly 4 bytes on the wire");
_Static_assert(sizeof(unsigned int) == 4,
               "the integer pipe imports carry a 32-bit store");
_Static_assert(GF_WGPIPE_IS_FP(1.0f) == 1,
               "a float store must route to the f32 import");
_Static_assert(GF_WGPIPE_IS_FP(1.0) == 1,
               "a double store must route to the f32 import");
_Static_assert(GF_WGPIPE_IS_FP(1u) == 0,
               "an unsigned store must route to the integer import");
_Static_assert(GF_WGPIPE_IS_FP((char)1) == 0,
               "a narrow integer store must route to the integer import");
_Static_assert(GF_WGPIPE_IS_FP((unsigned long long)1) == 0,
               "a wide integer store must route to the integer import");
_Static_assert(GF_WGPIPE_IS_FP((void *)0) == 0,
               "a pointer store must route to the integer import");
_Static_assert(GF_WGPIPE_AS_U32(0x1234abcdu) == 0x1234abcdu,
               "the integer conversion is value-preserving for 32-bit integers");
_Static_assert((unsigned int)((unsigned char)0x1ff) == 0xffu,
               "the 8-bit narrowing this header performs is the C conversion");

#endif /* GF_GX_WGPIPE_H */
