// Generated by scripts/gen-camera-mode1-constants.mjs.
// Source: user-data/GG4E/disc/sys/boot.dol; research/decomp/ghidra-export/chunk_0001.c
// Do not hand-edit; rerun the generator after updating decomp/DOL evidence.

export const CAMERA_MODE1_SOURCE = {
  bootDolPath: "user-data/GG4E/disc/sys/boot.dol",
  bootDolSha1: "91b32873d62ae25c0a9b08d665e1e8c19ae38a5f",
  decompPath: "research/decomp/ghidra-export/chunk_0001.c",
  decompSha1: "eedfd47f4b330298680339d2e77a3c236dd957f0",
  functions: [
    { address: "0x8000bda4", name: "zz_000bda4_" },
    { address: "0x8000c660", name: "FUN_8000c660" },
    { address: "0x8000c918", name: "FUN_8000c918" },
    { address: "0x8000c988", name: "FUN_8000c988" },
  ],
  description: "ROM-confirmed float constants for the mode-1 battle-camera follow blend.",
} as const;

export const CAMERA_MODE1_ROM_CONSTANTS = {
  FLOAT_80436ac4: { address: "0x80436ac4", value: 0.5, role: "half blend used by camera target-height updates" },
  FLOAT_80436acc: { address: "0x80436acc", value: 4, role: "mode-1 previous eye weight" },
  FLOAT_80436ad8: { address: "0x80436ad8", value: 0.0010000000474974513, role: "mode-1 vector epsilon" },
  FLOAT_80436ae0: { address: "0x80436ae0", value: 80, role: "mode-1 minimum camera distance" },
  FLOAT_80436ae4: { address: "0x80436ae4", value: 0.8999999761581421, role: "mode-1 distance decay multiplier" },
  FLOAT_80436ae8: { address: "0x80436ae8", value: 5, role: "mode-1 eye blend denominator" },
} as const;

/** FUN_8000c988: eye = (prevEye * FLOAT_80436acc + goalEye) / FLOAT_80436ae8. */
export const CAMERA_MODE1_PREVIOUS_EYE_WEIGHT = 4;

/** FUN_8000c988 denominator for the previous-eye blend. */
export const CAMERA_MODE1_EYE_BLEND_DENOMINATOR = 5;

/** FLOAT_80436ac4, used by mode-1 target-height blend paths. */
export const CAMERA_MODE1_HALF_BLEND = 0.5;

/** FLOAT_80436ae0, minimum mode-1 camera distance before decay logic. */
export const CAMERA_MODE1_MIN_DISTANCE = 80;

/** FLOAT_80436ae4, mode-1 camera distance decay multiplier. */
export const CAMERA_MODE1_DISTANCE_DECAY = 0.8999999761581421;
