// Generated by scripts/gen-cue-resolver-table.mjs from user-data/GG4E/disc/sys/boot.dol.
// Do not hand-edit; rerun the generator after updating DOL/decomp evidence.
//
// Resolution mechanism (ROM-faithful 1:1): the cue id passed to playSound IS the soundId.
// zz_00efb3c_ (chunk_0026.c:435) guards soundId<0x180 and splits bank=soundId>>7,
// sample=soundId&0x7f, routed through DAT_802d0bec[bank] (the table below). There is no
// cue→sound lookup table in the DOL — only this bank-routing table.

export const CUE_RESOLVER_SOURCE = {
  "bootDolPath": "user-data/GG4E/disc/sys/boot.dol",
  "bootDolSha1": "91b32873d62ae25c0a9b08d665e1e8c19ae38a5f",
  "evidence": "zz_00f036c_ (chunk_0026.c:792) forwards cueId verbatim to zz_00efb3c_ (chunk_0026.c:435), which guards (int)soundId<0x180 and decomposes bank=soundId>>7, sample=soundId&0x7f, then routes via DAT_802d0bec[bank]={tsb,chd,dpk} (chunk_0005.c:706). No cue→sound table exists; the cue IS the soundId.",
  "addresses": {
    "bankTable": "0x802d0bec"
  },
  "generatedBy": "gen-cue-resolver-table.mjs"
} as const;

// DAT_802d0bec — 4 banks × 3 big-endian u16 (tsb/chd/dpk AFS member indices). Read as
// short* (stride 3) at chunk_0005.c:706: banks 0..2 = battle/title, bank 3 = menu.
export const CUE_BANK_TABLE = [
  {
    "bank": 0,
    "soundbank": "snd_com01",
    "tsb": 2839,
    "chd": 2840,
    "dpk": 2841
  },
  {
    "bank": 1,
    "soundbank": "snd_com02",
    "tsb": 2842,
    "chd": 2843,
    "dpk": 2844
  },
  {
    "bank": 2,
    "soundbank": "snd_com03",
    "tsb": 2845,
    "chd": 2846,
    "dpk": 2847
  },
  {
    "bank": 3,
    "soundbank": "snd_com04",
    "tsb": 2848,
    "chd": 2849,
    "dpk": 2850
  }
] as const;

// zz_00efb3c_ guard immediate (chunk_0026.c:440): soundIds >= 0x180 are silently dropped.
// 0x180>>7 == 3, so exactly banks 0,1,2 are reachable via playSound; bank 3 (menu) is
// only attached via the param_9!=0 branch of zz_0043390_ and never dispatched by playSound.
export const CUE_MAX_SOUND_ID = 0x180 as const;
export const CUE_BANK_SHIFT = 7 as const;
export const CUE_SAMPLE_MASK = 0x7f as const;
export const CUE_BATTLE_BANK_COUNT = 3 as const;
