// =============================================================================
// inventory.generated.ts — GENERATED by scripts/hle-call-inventory.mjs.
// DO NOT EDIT BY HAND; re-run the script instead.
//
// The measured Audio (AI / AR / ARQ / DSP / OS audio system) surface of Gotcha Force: every entry point in this
// family that ROM GAME code calls, ranked by static call-site count, plus every
// hardware register in this family's MMIO windows that the corpus touches.
// This is the ranked list the HLE host's work is prioritized by, and the
// denominator its coverage percentage is computed against — so the coverage
// number is DERIVED from a measurement rather than asserted.
//
// SEAM CLASS matters here in a way it did not for GX:
//   "bridged"   — gnt4_*-prefixed, excluded from porting (design V2 F2), so
//                 every call crosses the H2 bridge and needs a host adapter.
//   "in-window" — ordinary ROM code the port compiles into the module. Calls
//                 to it do NOT cross the seam; it is listed because its body
//                 reaches hardware through the MMIO registers below.
//
// HONESTY NOTE (repeated from the generator): these are STATIC counts — how
// many PLACES in the ROM do the thing, not how often it executes. A per-frame
// frequency ranking requires a Dolphin trace and does not exist yet.
//
// Corpus: research/decomp/ghidra-export
// Symbols in the DOL:            26
// Called by game code:           20
// Game call sites:               40
//   of which bridged (seam):     6
//   of which in-window (no seam):34
// MMIO registers touched:        18 (403 reads, 342 writes)
// =============================================================================

export interface HleInventoryEntry {
  /** The C symbol as it appears in the corpus (and as a wasm import name). */
  readonly symbol: string;
  /** The entry point's real GameCube address in this game's DOL. */
  readonly romAddr: number | null;
  /** Whether a call to it crosses the SDK seam at all. */
  readonly seam: "bridged" | "in-window";
  /** Static call sites in ROM game code — the ranking key. */
  readonly gameCalls: number;
  /** Static call sites inside other gnt4_* SDK/HSD functions (context only). */
  readonly sdkInternalCalls: number;
  /** Distinct ROM functions that call it. */
  readonly distinctGameCallers: number;
}

export interface HleMmioEntry {
  /** The memory-mapped register address. */
  readonly register: number;
  /** Which hardware block it belongs to. */
  readonly window: string;
  /** Static lines that read it. */
  readonly reads: number;
  /** Static lines that write it. */
  readonly writes: number;
  /** Distinct ROM functions that touch it. */
  readonly functions: number;
}

/** Audio (AI / AR / ARQ / DSP / OS audio system) entry points called by ROM game code, ranked by static call sites. */
export const AUDIO_CALL_INVENTORY: readonly HleInventoryEntry[] = [
  { symbol: "AISetStreamVolLeft", romAddr: 0x802149c0, seam: "in-window", gameCalls: 10, sdkInternalCalls: 0, distinctGameCallers: 6 },
  { symbol: "AIInitDMA", romAddr: 0x80214634, seam: "in-window", gameCalls: 4, sdkInternalCalls: 0, distinctGameCallers: 3 },
  { symbol: "__AI_SRC_INIT", romAddr: 0x80214cd8, seam: "in-window", gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 3 },
  { symbol: "AIGetStreamPlayState", romAddr: 0x802149b0, seam: "in-window", gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 3 },
  { symbol: "ARAlloc", romAddr: 0x80214ff0, seam: "in-window", gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 3 },
  { symbol: "AISetStreamPlayState", romAddr: 0x802146d4, seam: "in-window", gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4___OSStopAudioSystem_bl", romAddr: 0x80200518, seam: "bridged", gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "__AI_set_stream_sample_rate", romAddr: 0x802148b0, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "__AICallbackStackSwitch", romAddr: 0x80214c80, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "__ARChecksize", romAddr: 0x80215208, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "AIGetDSPSampleRate", romAddr: 0x8021489c, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "AIInit", romAddr: 0x802149ec, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "AISetDSPSampleRate", romAddr: 0x802147bc, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "AIStartDMA", romAddr: 0x802146bc, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "ARFree", romAddr: 0x80215058, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "ARInit", romAddr: 0x802150cc, seam: "in-window", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4___OSInitAudioSystem_bl", romAddr: 0x8020035c, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_ARQInit_bl", romAddr: 0x80216bcc, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_OSGetSoundMode_bl", romAddr: 0x80205750, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_OSSetSoundMode_bl", romAddr: 0x802057d0, seam: "bridged", gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
];

/** Hardware registers in this family's MMIO windows that the corpus touches. */
export const AUDIO_MMIO_INVENTORY: readonly HleMmioEntry[] = [
  { register: 0xcc005028, window: "DSP", reads: 105, writes: 107, functions: 3 },
  { register: 0xcc00500a, window: "DSP", reads: 95, writes: 53, functions: 10 },
  { register: 0xcc005020, window: "DSP", reads: 72, writes: 72, functions: 4 },
  { register: 0xcc005024, window: "DSP", reads: 70, writes: 72, functions: 3 },
  { register: 0xcc006c00, window: "AI", reads: 29, writes: 21, functions: 11 },
  { register: 0xcc006c04, window: "AI", reads: 6, writes: 4, functions: 5 },
  { register: 0xcc005004, window: "DSP", reads: 6, writes: 0, functions: 4 },
  { register: 0xcc005036, window: "DSP", reads: 3, writes: 3, functions: 3 },
  { register: 0xcc006c08, window: "AI", reads: 5, writes: 0, functions: 2 },
  { register: 0xcc005000, window: "DSP", reads: 1, writes: 3, functions: 4 },
  { register: 0xcc005012, window: "DSP", reads: 2, writes: 2, functions: 2 },
  { register: 0xcc00501a, window: "DSP", reads: 2, writes: 1, functions: 1 },
  { register: 0xcc005030, window: "DSP", reads: 2, writes: 1, functions: 2 },
  { register: 0xcc005032, window: "DSP", reads: 2, writes: 1, functions: 2 },
  { register: 0xcc005006, window: "DSP", reads: 2, writes: 0, functions: 2 },
  { register: 0xcc005002, window: "DSP", reads: 0, writes: 1, functions: 1 },
  { register: 0xcc005016, window: "DSP", reads: 1, writes: 0, functions: 1 },
  { register: 0xcc006c0c, window: "AI", reads: 0, writes: 1, functions: 1 },
];

/** Total static game-code call sites across the whole ranked surface.
 *  Widened to `number` deliberately: a literal type here would make the
 *  divide-by-zero guard below a compile error rather than a guard. */
export const AUDIO_GAME_CALL_SITES: number = 40;

/** Static game-code call sites that actually CROSS the seam (gnt4_* callees). */
export const AUDIO_BRIDGED_GAME_CALL_SITES: number = 6;

/** Look one entry point up by symbol. */
export function audioInventoryEntry(symbol: string): HleInventoryEntry | undefined {
  return AUDIO_CALL_INVENTORY.find((e) => e.symbol === symbol);
}

/**
 * Coverage of the ranked surface, by BOTH measures that matter: how many
 * distinct entry points are implemented, and what share of the ROM's static
 * call sites they account for (weighted coverage). Reporting only the first
 * understates a steep distribution; reporting only the second hides a long
 * unimplemented tail. The host reports both, always together.
 */
export function audioCoverage(implemented: Iterable<string>): {
  implementedSymbols: number;
  totalSymbols: number;
  symbolPct: number;
  coveredCallSites: number;
  totalCallSites: number;
  callSitePct: number;
} {
  const set = new Set(implemented);
  const covered = AUDIO_CALL_INVENTORY.filter((e) => set.has(e.symbol));
  const coveredCallSites = covered.reduce((sum, e) => sum + e.gameCalls, 0);
  const totalSymbols = AUDIO_CALL_INVENTORY.length;
  return {
    implementedSymbols: covered.length,
    totalSymbols,
    symbolPct: totalSymbols === 0 ? 0 : Math.round((covered.length / totalSymbols) * 1000) / 10,
    coveredCallSites,
    totalCallSites: AUDIO_GAME_CALL_SITES,
    callSitePct:
      AUDIO_GAME_CALL_SITES === 0 ? 0 : Math.round((coveredCallSites / AUDIO_GAME_CALL_SITES) * 1000) / 10,
  };
}
