#!/usr/bin/env python3
"""Deobfuscate Ghidra C exports using a local OpenAI-compatible LLM (e.g. LM Studio).

Usage:
    python deobfuscate.py <input.c> [output.c]
    python deobfuscate.py --batch <glob>

The script sends the decompiled C to the local LLM and streams back a cleaner
version with better variable names, types, and comments.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Iterable

try:
    import requests
except ImportError:  # pragma: no cover
    print("requests required: pip install requests", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

API_BASE = os.environ.get("LLM_API_BASE", "http://localhost:1234/v1")
API_KEY = os.environ.get("LLM_API_KEY", "lm-studio")
MODEL = os.environ.get("LLM_MODEL", "qwen/qwen3.6-35b-a3b")
TIMEOUT = int(os.environ.get("LLM_TIMEOUT", "120"))
MAX_RETRIES = int(os.environ.get("LLM_MAX_RETRIES", "3"))
MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "8192"))
TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.3"))

PROMPT_TEMPLATE = """You are an expert reverse engineer working on a GameCube game.
The following C code was auto-generated by Ghidra from PPC PowerPC disassembly.

Your task:
1. Give meaningful names to functions and variables.
2. Replace `undefined8`, `undefined4`, etc. with proper types where possible.
3. Simplify obfuscated control flow if safe.
4. Add concise comments explaining the logic.
5. Keep the same overall structure and behavior.
6. Output ONLY the deobfuscated C code, no markdown.

Input code:
```c
{code}
```
"""  # fmt: skip


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------

def _api_chat(messages: list[dict[str, str]], stream: bool = True) -> str:
    url = atmospheric_url()
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {API_KEY}",
    }
    payload = {
        "model": MODEL,
        "messages": messages,
        "temperature": TEMPERATURE,
        "max_tokens": MAX_TOKENS,
        "stream": stream,
    }

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            resp = requests.post(url, headers=headers, json=payload, stream=stream, timeout=TIMEOUT)
            resp.raise_for_status()
            if stream:
                return _read_stream(resp)
            data = resp.json()
            return data["choices"][0]["message"]["content"]
        except requests.exceptions.ConnectionError as exc:
            print(f"[warn] connection error (attempt {attempt}/{MAX_RETRIES}): {exc}", file=sys.stderr)
        except requests.exceptions.HTTPError as exc:
            print(f"[warn] HTTP error (attempt {attempt}/{MAX_RETRIES}): {exc}", file=sys.stderr)
        if attempt < MAX_RETRIES:
            time.sleep(2 ** attempt)
        else:
            raise RuntimeError("LLM API unreachable after retries")
    return ""  # unreachable


def atmospheric_url() -> str:
    base = API_BASE.rstrip("/")
    if base.endswith("/v1"):
        return f"{base}/chat/completions"
    return f"{base}/v1/chat/completions"


def _read_stream(resp) -> str:
    chunks: list[str] = []
    for line in resp.iter_lines():
        if not line:
            continue
        line_str = line.decode("utf-8")
        if line_str.startswith("data: "):
            data = line_str[6:]
            if data.strip() == "[DONE]":
                break
            try:
                payload = json.loads(data)
                delta = payload.get("choices", [{}])[0].get("delta", {}).get("content", "")
                if delta:
                    sys.stdout.write(delta)
                    sys.stdout.flush()
                    chunks.append(delta)
            except json.JSONDecodeError:
                continue
    if chunks:
        sys.stdout.write("\n")
    return "".join(chunks)


def deobfuscate(code: str, *, stream: bool = True) -> str:
    prompt = PROMPT_TEMPLATE.format(code=code)
    messages = [
        {"role": "system", "content": "You are a helpful reverse engineering assistant."},
        {"role": "user", "content": prompt},
    ]
    return _api_chat(messages, stream=stream)


def clean_markdown_fence(text: str) -> str:
    text = re.sub(r"^\s*```c?\n", "", text)
    text = re.sub(r"\n?\s*```$", "", text)
    return text


# ---------------------------------------------------------------------------
# Batch / CLI
# ---------------------------------------------------------------------------

def glob_files(pattern: str, root: Path = Path.cwd()) -> Iterable[Path]:
    if "*" in pattern or "?" in pattern:
        for path in root.rglob("*"):
            if path.is_file() and fnmatch.fnmatch(str(path.relative_to(root)), pattern):
                yield path
    else:
        p = Path(pattern)
        if p.is_file():
            yield p


def process_file(input_path: Path, output_path: Path | None, *, stream: bool = True) -> str:
    print(f"[{input_path}] -> reading …", file=sys.stderr)
    code = input_path.read_text(encoding="utf-8")
    result = deobfuscate(code, stream=stream)
    clean = clean_markdown_fence(result)
    if output_path:
        output_path.write_text(clean, encoding="utf-8")
        print(f"[{input_path}] -> written {output_path}", file=sys.stderr)
    return clean


def main() -> None:  # pragma: no cover
    parser = argparse.ArgumentParser(description="Deobfuscate Ghidra C exports via local LLM")
    parser.add_argument("input", help="Input .c file or glob pattern (with --batch)")
    parser.add_argument("output", nargs="?", help="Optional output .c file")
    parser.add_argument("--batch", action="store_true", help="Treat input as glob and process all matches")
    parser.add_argument("--no-stream", action="store_true", help="Disable streaming (wait for full response)")
    args = parser.parse_args()

    stream = not args.no_stream

    if args.batch:
        matches = list(glob_files(args.input))
        if not matches:
            print(f"No files matched pattern: {args.input}", file=sys.stderr)
            sys.exit(1)
        for idx, path in enumerate(matches, 1):
            out = path.with_suffix(".clean.c") if args.output is None else Path(args.output)
            process_file(path, out, stream=stream)
    else:
        process_file(Path(args.input), Path(args.output) if args.output else None, stream=stream)


if __name__ == "__main__":
    main()
