#!/usr/bin/env node
// Reorganize the flat Ghidra bulk-decompile export (research/decomp/ghidra-export/chunk_*.c)
// into a browsable per-system / per-function tree. Pure deterministic text processing —
// no LLM involvement, safe to re-run any time the export is regenerated.
//
// Output: research/decomp/organized/
//   <bucket>/<address>_<name>.c     one file per function
//   _map.tsv                        address, name, alias, bucket, relative path
//   _summary.md                     per-bucket counts
//
// Buckets are assigned from the symbol name (community GG4E-CSM map prefixes for the
// GameCube SDK / HSD engine) and fall through to game-code address bands for the
// anonymous zz_/FUN_ functions.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const exportDir = path.join(repoRoot, "research", "decomp", "ghidra-export");
const outDir = path.join(repoRoot, "research", "decomp", "organized");

// name-prefix → bucket (checked in order, first match wins)
const PREFIX_BUCKETS = [
  [/^HSD_/, "sdk-hsd"], // HAL sysdolphin scene-graph/render engine
  [/^(GX|GD)[A-Z_]/, "sdk-gx"], // GPU pipeline
  [/^(OS|DVD|VI|PAD|SI|EXI|CARD|ARQ?|DSP|IRQ|DB|__OS|SC[A-Z])/, "sdk-os"],
  [/^(AX|AXFX|AI[A-Z_]|Mix|SND|JAX|sndConvert|seqp?_|synth)/i, "sdk-audio"],
  [/^(PSMTX|C_MTX|MTX|PSVEC|VEC|QUAT|C_VEC|MTXQuat)/, "sdk-math"],
  [/^(mem(cpy|set|move|cmp)|str[a-z]+|s?printf|vprintf|atoi|atof|ato[lx]|rand|srand|qsort|bsearch|toupper|tolower|is[a-z]+|abs|labs|div|ldiv|calloc|malloc|free|realloc|exit|abort|assert|setjmp|longjmp|errno|_[_a-z])/,
    "sdk-libc"],
  [/^(fn_|fabs|sqrtf?|sinf?|cosf?|tanf?|atan2?f?|asinf?|acosf?|powf?|expf?|logf?|floorf?|ceilf?|fmodf?|frexp|ldexp|modff?)/,
    "sdk-libc"],
  [/^gnt4_/, "engine-shared"], // names borrowed from the GNT4 map (shared HAL/AM2 engine code)
];

// address-band → bucket for anonymous game code (zz_*/FUN_*). Bands derived from
// systems already confirmed in behavior-notes.md / challenge-flow-evidence.
const ADDRESS_BANDS = [
  [0x80020000, 0x8004a000, "game-combat"], // hit resolution, damage, knockback, borg state
  [0x8004a000, 0x80060000, "game-battle"], // battle/slot setup, spawning
  [0x80060000, 0x800a0000, "game-systems"],
  [0x80190000, 0x801a0000, "game-modes"], // challenge/adventure flow lives here
  [0x801a0000, 0x80230000, "game-ui"],
];

function bucketFor(name, addr) {
  // The community map wraps borrowed GNT4/SDK symbols as `gnt4-<RealSymbol>-suffix`;
  // unwrap so the real symbol prefix drives classification.
  let sym = name;
  if (sym.startsWith("gnt4-")) sym = sym.slice(5).split("-")[0];
  if (/^(HSD_|_HSD|JObj|cbF)/.test(sym)) return "sdk-hsd";
  if (/^(PPC|__PPC)/.test(sym)) return "sdk-os";
  for (const [re, bucket] of PREFIX_BUCKETS) if (re.test(sym)) return bucket;
  if (sym !== name) return "engine-shared"; // gnt4-mapped but no SDK prefix matched
  if (/^TRK/.test(sym)) return "sdk-os"; // MetroTRK debug stub
  for (const [lo, hi, bucket] of ADDRESS_BANDS) if (addr >= lo && addr < hi) return bucket;
  return "game-unsorted";
}

function sanitize(name) {
  return name.replace(/[^A-Za-z0-9_.-]/g, "_").slice(0, 80);
}

// ---- parse every chunk into { addr, name, body } records ----
const HEADER_RE = /^\/\/ ==== ([0-9a-f]{8})  (.+?) ====\s*$/;
const records = [];
for (const file of fs.readdirSync(exportDir).filter((f) => /^chunk_\d+\.c$/.test(f)).sort()) {
  const lines = fs.readFileSync(path.join(exportDir, file), "utf8").split(/\r?\n/);
  let cur = null;
  for (const line of lines) {
    const m = HEADER_RE.exec(line);
    if (m) {
      if (cur) records.push(cur);
      cur = { addr: m[1], name: m[2].trim(), lines: [line], srcChunk: file };
    } else if (cur) {
      cur.lines.push(line);
    }
  }
  if (cur) records.push(cur);
}

// ---- write the tree ----
fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

const mapRows = [["address", "name", "alias", "bucket", "path", "src_chunk"].join("\t")];
const counts = new Map();

for (const rec of records) {
  const body = rec.lines.join("\n").replace(/\n+$/, "") + "\n";
  const alias = /GF_ALIAS:\s*([A-Za-z0-9_]+)/.exec(body)?.[1] ?? "";
  const bucket = bucketFor(rec.name, parseInt(rec.addr, 16));
  const fileName = `${rec.addr}_${sanitize(alias || rec.name)}.c`;
  const dir = path.join(outDir, bucket);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, fileName), body);
  mapRows.push([rec.addr, rec.name, alias, bucket, `${bucket}/${fileName}`, rec.srcChunk].join("\t"));
  counts.set(bucket, (counts.get(bucket) ?? 0) + 1);
}

fs.writeFileSync(path.join(outDir, "_map.tsv"), mapRows.join("\n") + "\n");

const summary = [
  "# Organized decomp tree",
  "",
  `Generated by \`scripts/reorg-decomp.mjs\` from ${records.length} functions in research/decomp/ghidra-export/.`,
  "Re-run the script after any re-export; this tree is derived output, never hand-edited.",
  "",
  "| bucket | functions |",
  "|---|---|",
  ...[...counts.entries()].sort((a, b) => b[1] - a[1]).map(([b, n]) => `| ${b} | ${n} |`),
  "",
].join("\n");
fs.writeFileSync(path.join(outDir, "_summary.md"), summary);

console.log(`wrote ${records.length} functions into ${counts.size} buckets under research/decomp/organized/`);
for (const [b, n] of [...counts.entries()].sort((a, b) => b[1] - a[1])) console.log(`  ${b}: ${n}`);
