// Generated by scripts/gen-knockback-direction-data.mjs.
// Source: research/decomp/data/knockback-direction-800300bc.json (0x800300bc)
// Do not hand-edit; rerun the generator after updating decomp data.

export const KNOCKBACK_DIRECTION_SOURCE = {
  address: "0x800300bc",
  sourcePath: "research/decomp/data/knockback-direction-800300bc.json",
  sourceSha1: "7fff36820530c9d23d2ba477f27cbfbf15494953",
  modeValues: [0,1,2,3,4],
  modeCount: 5,
  description: "ROM-confirmed constants and mode values for zz_00300bc_ knockback/launch direction.",
} as const;

/** FLOAT_8043707c: radians to BAM16 conversion. */
export const BAM16_PER_RADIAN = 10430.3779296875;

/** FLOAT_80436fc0: degenerate-vector magnitude-squared threshold. */
export const DEGENERATE_MAG_SQ_THRESHOLD = 0.009999999776482582;

/** FLOAT_80436f68/FLOAT_80436f74: fallback vector when the source vector is degenerate. */
export const FALLBACK_DIR_COMPONENTS = {
  x: 0,
  y: 0,
  z: -1,
} as const;

export const BAM16_WRAP = 0x10000;
