// Generated by scripts/gen-challenge-menu-object-tables.mjs from user-data/GG4E/disc/sys/boot.dol.
// Do not hand-edit; rerun the generator after updating DOL/decomp evidence.

export const CHALLENGE_MENU_OBJECT_TABLES_SOURCE = {
  "bootDolPath": "user-data/GG4E/disc/sys/boot.dol",
  "bootDolSha1": "91b32873d62ae25c0a9b08d665e1e8c19ae38a5f",
  "evidence": "spawn_challenge_menu_object @0x80199b60 reads 16-byte records at DAT_80370f28 (modelIds +0..7, modelCount +8, allocKind +9, initFn +0xc); dispatch_challenge_menu_object_state @0x80199c0c uses PTR_FUN_80370fa8[state]; load_models tail-calls PTR_FUN_80370fb8[type]; update_animation uses PTR_FUN_80370fd8[type]; obj0 init/update read FLOAT_8043b370..b390 + DOUBLE_8043b388.",
  "addresses": {
    "objectRecords": "0x80370f28",
    "stateDispatch": "0x80370fa8",
    "loadModelsDispatch": "0x80370fb8",
    "updateAnimDispatch": "0x80370fd8",
    "floatBlock": "0x8043b370",
    "timingDouble": "0x8043b388",
    "blinkFloat": "0x8043b390"
  },
  "generatedBy": "gen-challenge-menu-object-tables.mjs"
} as const;

export const CHALLENGE_MENU_OBJECT_RECORDS = [
  {
    "type": 0,
    "modelIds": [
      2,
      3,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "modelCount": 2,
    "allocKind": 2,
    "initFn": "0x8019a064"
  },
  {
    "type": 1,
    "modelIds": [
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0
    ],
    "modelCount": 3,
    "allocKind": 2,
    "initFn": "0x8019a330"
  },
  {
    "type": 2,
    "modelIds": [
      -1,
      -1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "modelCount": 3,
    "allocKind": 2,
    "initFn": "0x8019ac1c"
  },
  {
    "type": 3,
    "modelIds": [
      13,
      -1,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "modelCount": 2,
    "allocKind": 2,
    "initFn": "0x8019afa8"
  },
  {
    "type": 4,
    "modelIds": [
      18,
      16,
      17,
      0,
      0,
      0,
      0,
      0
    ],
    "modelCount": 3,
    "allocKind": 2,
    "initFn": "0x8019b228"
  },
  {
    "type": 5,
    "modelIds": [
      -1,
      -1,
      -1,
      -1,
      -1,
      0,
      0,
      0
    ],
    "modelCount": 5,
    "allocKind": 2,
    "initFn": "0x8019b718"
  },
  {
    "type": 6,
    "modelIds": [
      -1,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "modelCount": 1,
    "allocKind": 2,
    "initFn": "0x8019bae8"
  }
] as const;

export const CHALLENGE_MENU_OBJECT_STATE_DISPATCH = [
  {
    "index": 0,
    "address": "0x80199c74"
  },
  {
    "index": 1,
    "address": "0x80199d30"
  },
  {
    "index": 2,
    "address": "0x80199d6c"
  },
  {
    "index": 3,
    "address": "0x80199d80"
  }
] as const;

export const CHALLENGE_MENU_OBJECT_LOAD_MODELS_DISPATCH = [
  {
    "index": 0,
    "address": "0x80199dc0"
  },
  {
    "index": 1,
    "address": "0x8019a108"
  },
  {
    "index": 2,
    "address": "0x8019a3f0"
  },
  {
    "index": 3,
    "address": "0x8019ae00"
  },
  {
    "index": 4,
    "address": "0x8019b030"
  },
  {
    "index": 5,
    "address": "0x8019b358"
  },
  {
    "index": 6,
    "address": "0x8019b8a4"
  },
  {
    "index": 7,
    "address": "0x8019bc4c"
  }
] as const;

export const CHALLENGE_MENU_OBJECT_UPDATE_ANIM_DISPATCH = [
  {
    "index": 0,
    "address": "0x80199ea8"
  },
  {
    "index": 1,
    "address": "0x8019a2c8"
  },
  {
    "index": 2,
    "address": "0x8019a8f0"
  },
  {
    "index": 3,
    "address": "0x8019afa4"
  },
  {
    "index": 4,
    "address": "0x8019b094"
  },
  {
    "index": 5,
    "address": "0x8019b6c0"
  },
  {
    "index": 6,
    "address": "0x8019b9ec"
  },
  {
    "index": 7,
    "address": "0x8019bdc0"
  }
] as const;

/** DAT_803bb384 is RUNTIME state (.bss, not a DOL constant): the archive/scene id the
 * model loader reads at call time. Ports must take it from the runtime work block. */
export const CHALLENGE_MENU_OBJECT_MODEL_ARCHIVE_ID_ADDR = "0x803bb384" as const;

export const CHALLENGE_MENU_OBJECT_LAYOUT_FLOATS = [
  0,
  -75,
  1,
  -301,
  0.5,
  -300
] as const;

export const CHALLENGE_MENU_OBJECT_TIMING_DOUBLE = 4503601774854144 as const;

export const CHALLENGE_MENU_OBJECT_BLINK_FLOAT = 0.8999999761581421 as const;

