// Generated by scripts/gen-challenge-flow-tables.mjs from user-data/GG4E/disc/sys/boot.dol.
// Do not hand-edit; rerun the generator after updating DOL/decomp evidence.

export const CHALLENGE_FLOW_TABLES_SOURCE = {
  "bootDolPath": "user-data/GG4E/disc/sys/boot.dol",
  "bootDolSha1": "91b32873d62ae25c0a9b08d665e1e8c19ae38a5f",
  "evidence": "dispatch_challenge_flow_state @0x80195f2c dispatches via PTR_FUN_8036f560[mode]; poll_challenge_menu_selection @0x80196030 reads DAT_804356d0 + DAT_8036f554; build_challenge_battle_setup @0x801962c4 reads the PTR_DAT_8036f40c/f434/f3e4/f4b8/f53c pointer arrays; zz_0196dac_ @0x80196dac reads DAT_8036f548 (11-byte).",
  "addresses": {
    "flowModeDispatch": "0x8036f560",
    "flowSubDispatch": "0x8036f580",
    "actorActionDispatch": "0x8036f5a8",
    "challengeTypeList": "0x8036f548",
    "startForceEnergy": "0x8036f554",
    "battleCountByDifficulty": "0x804356d0",
    "stageIdPairByDifficulty": "0x804356e4",
    "slotFlagByDifficulty": "0x804356ec",
    "stageStructA": "0x804356f4",
    "stageStructB": "0x804356fc",
    "sceneObjStruct": "0x8036f58c",
    "allyCountByBattle": "0x8036f40c",
    "enemyCountByBattle": "0x8036f434",
    "allyBudgetByBattle": "0x8036f4b8",
    "enemyBudgetByBattle": "0x8036f53c",
    "allyPoolGroupTable": "0x8036f360",
    "enemyPoolGroupTable": "0x8036f3e4"
  },
  "generatedBy": "gen-challenge-flow-tables.mjs"
} as const;

export const CHALLENGE_FLOW_MODE_DISPATCH = [
  {
    "index": 0,
    "address": "0x80195fbc"
  },
  {
    "index": 1,
    "address": "0x80196030"
  },
  {
    "index": 2,
    "address": "0x80196188"
  },
  {
    "index": 3,
    "address": "0x801962c4"
  },
  {
    "index": 4,
    "address": "0x8019688c"
  },
  {
    "index": 5,
    "address": "0x80196a9c"
  },
  {
    "index": 6,
    "address": "0x80196cec"
  },
  {
    "index": 7,
    "address": "0x80196d64"
  }
] as const;

export const CHALLENGE_FLOW_SUB_DISPATCH = [
  {
    "index": 0,
    "address": "0x801968cc"
  },
  {
    "index": 1,
    "address": "0x80196948"
  },
  {
    "index": 2,
    "address": "0x801969a0"
  },
  {
    "index": 3,
    "address": "0x00000000"
  }
] as const;

export const CHALLENGE_ACTOR_ACTION_DISPATCH = [
  {
    "index": 0,
    "address": "0x80197190"
  },
  {
    "index": 1,
    "address": "0x80197278"
  },
  {
    "index": 2,
    "address": "0x801977a4"
  },
  {
    "index": 3,
    "address": "0x801977b4"
  },
  {
    "index": 4,
    "address": "0x001fe800"
  },
  {
    "index": 5,
    "address": "0x00018000"
  },
  {
    "index": 6,
    "address": "0x00000000"
  },
  {
    "index": 7,
    "address": "0x00000000"
  }
] as const;

export const CHALLENGE_TYPE_LIST = [
  0,
  1,
  2,
  3,
  4,
  5,
  8,
  10,
  11,
  12,
  14
] as const;

export const CHALLENGE_START_FORCE_ENERGY = [
  1500,
  2000,
  2500
] as const;

export const CHALLENGE_BATTLE_COUNT_BY_DIFFICULTY = [
  5,
  10,
  15
] as const;

export const CHALLENGE_STAGE_ID_PAIR_BY_DIFFICULTY = [
  0,
  31,
  10,
  5,
  28,
  4
] as const;

export const CHALLENGE_SLOT_FLAG_BY_DIFFICULTY = [
  7,
  4,
  7,
  7,
  7,
  12
] as const;

export const CHALLENGE_STAGE_STRUCT_A = [
  255,
  255,
  255,
  255,
  255,
  255,
  255,
  255
] as const;

export const CHALLENGE_STAGE_STRUCT_B = [
  0,
  0,
  0,
  0,
  2,
  128,
  1,
  192
] as const;

export const CHALLENGE_SCENE_OBJ_STRUCT = [
  0,
  0,
  1065353216,
  1142947840
] as const;

export const CHALLENGE_ALLY_COUNT_BY_BATTLE = [
  {
    "difficulty": 0,
    "pointer": "0x804356d4",
    "row": [
      4,
      4,
      5,
      5,
      5
    ]
  },
  {
    "difficulty": 1,
    "pointer": "0x8036f3f0",
    "row": [
      4,
      4,
      4,
      5,
      5,
      5,
      6,
      6,
      6,
      7
    ]
  },
  {
    "difficulty": 2,
    "pointer": "0x8036f3fc",
    "row": [
      4,
      4,
      4,
      4,
      4,
      4,
      4,
      4,
      5,
      5,
      5,
      5,
      5,
      5,
      5
    ]
  }
] as const;

export const CHALLENGE_ENEMY_COUNT_BY_BATTLE = [
  {
    "difficulty": 0,
    "pointer": "0x804356dc",
    "row": [
      10,
      10,
      8,
      8,
      1
    ]
  },
  {
    "difficulty": 1,
    "pointer": "0x8036f418",
    "row": [
      10,
      10,
      10,
      10,
      2,
      10,
      10,
      10,
      10,
      2
    ]
  },
  {
    "difficulty": 2,
    "pointer": "0x8036f424",
    "row": [
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10,
      10
    ]
  }
] as const;

export const CHALLENGE_ALLY_BUDGET_BY_BATTLE = [
  {
    "difficulty": 0,
    "pointer": "0x8036f440",
    "row": [
      1000,
      1000,
      1200,
      1200,
      1400
    ]
  },
  {
    "difficulty": 1,
    "pointer": "0x8036f454",
    "row": [
      1200,
      1200,
      1400,
      1400,
      1600,
      1600,
      1800,
      1800,
      2000,
      2200
    ]
  },
  {
    "difficulty": 2,
    "pointer": "0x8036f47c",
    "row": [
      800,
      900,
      1000,
      1100,
      1200,
      1300,
      1400,
      1500,
      1600,
      1700,
      1800,
      1900,
      2000,
      2100,
      2200
    ]
  }
] as const;

export const CHALLENGE_ENEMY_BUDGET_BY_BATTLE = [
  {
    "difficulty": 0,
    "pointer": "0x8036f4c4",
    "row": [
      1000,
      1000,
      1200,
      1200,
      1400
    ]
  },
  {
    "difficulty": 1,
    "pointer": "0x8036f4d8",
    "row": [
      1200,
      1200,
      1400,
      1400,
      1600,
      1600,
      1800,
      1800,
      2000,
      2200
    ]
  },
  {
    "difficulty": 2,
    "pointer": "0x8036f500",
    "row": [
      1400,
      1400,
      1600,
      1600,
      1800,
      1800,
      2000,
      2000,
      2200,
      2200,
      2400,
      2400,
      2600,
      2600,
      2800
    ]
  }
] as const;

export const CHALLENGE_ALLY_POOL_GROUP_TABLE = [
  {
    "difficulty": 0,
    "pointer": "0x8036f2e8",
    "row": [
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50,
      50
    ]
  },
  {
    "difficulty": 1,
    "pointer": "0x8036f2fc",
    "row": [
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      51,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52,
      52
    ]
  },
  {
    "difficulty": 2,
    "pointer": "0x8036f324",
    "row": [
      52,
      52,
      52,
      52,
      52,
      53,
      52,
      53,
      53,
      53,
      53,
      53,
      53,
      54,
      53,
      54,
      54,
      54,
      54,
      54,
      54,
      55,
      54,
      55,
      55,
      55,
      55,
      55,
      55,
      56,
      55,
      56,
      56,
      56,
      56,
      56,
      56,
      57,
      56,
      57,
      57,
      57,
      57,
      57,
      57,
      58,
      57,
      58,
      58,
      58,
      58,
      58,
      58,
      60,
      58,
      60,
      60,
      61,
      60,
      58
    ]
  }
] as const;

export const CHALLENGE_ENEMY_POOL_GROUP_TABLE = [
  {
    "difficulty": 0,
    "pointer": "0x8036f36c",
    "row": [
      48,
      48,
      48,
      48,
      49,
      49,
      49,
      49,
      50,
      50,
      50,
      50,
      51,
      51,
      51,
      51,
      64,
      64,
      64,
      64
    ]
  },
  {
    "difficulty": 1,
    "pointer": "0x8036f380",
    "row": [
      49,
      49,
      49,
      49,
      50,
      50,
      50,
      50,
      51,
      51,
      51,
      51,
      52,
      52,
      52,
      52,
      66,
      66,
      66,
      66,
      53,
      53,
      53,
      53,
      54,
      54,
      54,
      54,
      55,
      55,
      55,
      55,
      56,
      56,
      56,
      56,
      65,
      65,
      65,
      65
    ]
  },
  {
    "difficulty": 2,
    "pointer": "0x8036f3a8",
    "row": [
      50,
      50,
      50,
      50,
      51,
      51,
      51,
      51,
      52,
      52,
      52,
      52,
      54,
      54,
      54,
      54,
      67,
      67,
      67,
      67,
      64,
      53,
      53,
      53,
      55,
      68,
      55,
      55,
      56,
      56,
      69,
      56,
      58,
      58,
      58,
      64,
      66,
      66,
      66,
      66,
      57,
      57,
      69,
      57,
      59,
      68,
      59,
      59,
      60,
      60,
      66,
      60,
      65,
      61,
      61,
      61,
      61,
      61,
      61,
      61
    ]
  }
] as const;

