// Generated by scripts/gen-title-intro-script.mjs from user-data/GG4E/disc/sys/boot.dol.
// Do not hand-edit; rerun the generator after updating DOL/decomp evidence.

export const TITLE_INTRO_SCRIPT_SOURCE = {
  "bootDolPath": "user-data/GG4E/disc/sys/boot.dol",
  "bootDolSha1": "91b32873d62ae25c0a9b08d665e1e8c19ae38a5f",
  "evidence": "FUN_801c795c installs DAT_8038a3ec; zz_01c7de4_ dispatches via PTR_FUN_8038a4f8 and DAT_8038a3b8; FUN_801c81a0 handles opcode 0x0d actor controls.",
  "addresses": {
    "opcodeLengths": "0x8038a3b8",
    "script": "0x8038a3ec",
    "actorDescriptors": "0x8038a4ec",
    "opcodeHandlers": "0x8038a4f8",
    "widgetDescriptors": "0x8038a570"
  },
  "generatedBy": "gen-title-intro-script.mjs"
} as const;

export const TITLE_INTRO_OPCODE_LENGTHS = [
  1,
  5,
  0,
  0,
  0,
  2,
  1,
  3,
  1,
  1,
  0,
  0,
  1,
  3,
  1,
  1,
  0,
  2,
  0,
  2,
  1,
  2
] as const;

export const TITLE_INTRO_OPCODE_HANDLERS = [
  "0x801c7e64",
  "0x801c7eb8",
  "0x801c7f00",
  "0x801c7f28",
  "0x801c7f4c",
  "0x801c7f70",
  "0x801c7fc0",
  "0x801c7ffc",
  "0x801c809c",
  "0x801c80ec",
  "0x801c8100",
  "0x801c8128",
  "0x801c8168",
  "0x801c81a0",
  "0x801c8278",
  "0x801c82b0",
  "0x801c8328",
  "0x801c835c",
  "0x801c83b8",
  "0x801c83e4",
  "0x801c8434",
  "0x801c846c"
] as const;

export const TITLE_INTRO_SCRIPT_BYTES = [
  0,
  1,
  6,
  255,
  7,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  60,
  2,
  19,
  0,
  27,
  20,
  1,
  5,
  0,
  120,
  10,
  11,
  9,
  1,
  7,
  0,
  3,
  1,
  0,
  2,
  20,
  0,
  8,
  3,
  6,
  12,
  12,
  1,
  7,
  0,
  0,
  1,
  8,
  0,
  21,
  1,
  124,
  5,
  0,
  30,
  0,
  3,
  13,
  1,
  0,
  0,
  13,
  1,
  1,
  0,
  13,
  0,
  0,
  0,
  13,
  0,
  1,
  0,
  13,
  2,
  0,
  0,
  13,
  2,
  0,
  1,
  7,
  0,
  255,
  1,
  5,
  0,
  20,
  13,
  2,
  1,
  1,
  5,
  0,
  4,
  13,
  2,
  1,
  0,
  8,
  255,
  13,
  0,
  0,
  1,
  16,
  15,
  1,
  6,
  18,
  7,
  0,
  255,
  1,
  8,
  255,
  17,
  0,
  8,
  5,
  0,
  15,
  15,
  0,
  13,
  0,
  1,
  1,
  16,
  15,
  1,
  6,
  13,
  7,
  0,
  255,
  1,
  8,
  255,
  17,
  0,
  8,
  5,
  0,
  10,
  15,
  0,
  13,
  0,
  0,
  6,
  6,
  20,
  7,
  0,
  255,
  1,
  8,
  255,
  13,
  0,
  1,
  6,
  6,
  21,
  7,
  0,
  255,
  1,
  8,
  255,
  13,
  0,
  0,
  3,
  13,
  0,
  1,
  3,
  6,
  15,
  7,
  2,
  255,
  1,
  8,
  255,
  13,
  0,
  1,
  4,
  6,
  16,
  7,
  0,
  255,
  1,
  8,
  255,
  13,
  0,
  0,
  4,
  6,
  19,
  7,
  0,
  255,
  1,
  8,
  255,
  13,
  0,
  0,
  7,
  13,
  0,
  1,
  7,
  6,
  17,
  7,
  0,
  255,
  1,
  8,
  255,
  5,
  0,
  60,
  0,
  9,
  5,
  0,
  60,
  0,
  10,
  5,
  0,
  60,
  0,
  11,
  18,
  5,
  0,
  150,
  0,
  12,
  19,
  0,
  29,
  5,
  1,
  44,
  12,
  0,
  4
] as const;

export const TITLE_INTRO_ACTOR_DESCRIPTORS = [
  {
    "slot": 0,
    "rawBorgId": 1557,
    "borgId": "pl0615",
    "variant": 10
  },
  {
    "slot": 1,
    "rawBorgId": 65535,
    "borgId": null,
    "variant": null
  },
  {
    "slot": 2,
    "rawBorgId": 65535,
    "borgId": null,
    "variant": null
  }
] as const;

export const TITLE_INTRO_WIDGET_DESCRIPTORS = [
  {
    "index": 0,
    "modelId": 55,
    "updateKind": 0,
    "variant": 0
  },
  {
    "index": 1,
    "modelId": 65,
    "updateKind": 2,
    "variant": 0
  },
  {
    "index": 2,
    "modelId": 51,
    "updateKind": 1,
    "variant": 0
  },
  {
    "index": 3,
    "modelId": 52,
    "updateKind": 1,
    "variant": 1
  },
  {
    "index": 4,
    "modelId": 53,
    "updateKind": 1,
    "variant": 2
  },
  {
    "index": 5,
    "modelId": 54,
    "updateKind": 1,
    "variant": 3
  },
  {
    "index": 6,
    "modelId": 48,
    "updateKind": 1,
    "variant": 4
  },
  {
    "index": 7,
    "modelId": 49,
    "updateKind": 1,
    "variant": 5
  },
  {
    "index": 8,
    "modelId": 50,
    "updateKind": 1,
    "variant": 6
  },
  {
    "index": 9,
    "modelId": 47,
    "updateKind": 1,
    "variant": 7
  },
  {
    "index": 10,
    "modelId": -1,
    "updateKind": 0,
    "variant": 0
  }
] as const;

export const TITLE_INTRO_COMMANDS = [
  {
    "offset": 0,
    "frame": 0,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      1
    ]
  },
  {
    "offset": 2,
    "frame": 0,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      255
    ]
  },
  {
    "offset": 4,
    "frame": 0,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      0,
      0
    ]
  },
  {
    "offset": 8,
    "frame": 0,
    "opcode": 1,
    "name": "screenColor",
    "handler": "0x801c7eb8",
    "payload": [
      0,
      0,
      0,
      0,
      60
    ]
  },
  {
    "offset": 14,
    "frame": 0,
    "opcode": 2,
    "name": "waitForArchive",
    "handler": "0x801c7f00",
    "payload": []
  },
  {
    "offset": 15,
    "frame": 0,
    "opcode": 19,
    "name": "spawnTitleWidget",
    "handler": "0x801c83e4",
    "payload": [
      0,
      27
    ]
  },
  {
    "offset": 18,
    "frame": 0,
    "opcode": 20,
    "name": "setTitleWidgetMode",
    "handler": "0x801c8434",
    "payload": [
      1
    ]
  },
  {
    "offset": 20,
    "frame": 0,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      120
    ],
    "waitFrames": 120
  },
  {
    "offset": 23,
    "frame": 120,
    "opcode": 10,
    "name": "waitForCamera",
    "handler": "0x801c8100",
    "payload": []
  },
  {
    "offset": 24,
    "frame": 120,
    "opcode": 11,
    "name": "attachDeskArchives",
    "handler": "0x801c8128",
    "payload": []
  },
  {
    "offset": 25,
    "frame": 120,
    "opcode": 9,
    "name": "setCameraMode",
    "handler": "0x801c80ec",
    "payload": [
      1
    ]
  },
  {
    "offset": 27,
    "frame": 120,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      3,
      1
    ]
  },
  {
    "offset": 31,
    "frame": 120,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      2
    ]
  },
  {
    "offset": 33,
    "frame": 120,
    "opcode": 20,
    "name": "setTitleWidgetMode",
    "handler": "0x801c8434",
    "payload": [
      0
    ]
  },
  {
    "offset": 35,
    "frame": 120,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      3
    ]
  },
  {
    "offset": 37,
    "frame": 120,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      12
    ]
  },
  {
    "offset": 39,
    "frame": 120,
    "opcode": 12,
    "name": "setAudioCue",
    "handler": "0x801c8168",
    "payload": [
      1
    ]
  },
  {
    "offset": 41,
    "frame": 120,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      0,
      1
    ]
  },
  {
    "offset": 45,
    "frame": 120,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      0
    ]
  },
  {
    "offset": 47,
    "frame": 120,
    "opcode": 21,
    "name": "playSound",
    "handler": "0x801c846c",
    "payload": [
      1,
      124
    ]
  },
  {
    "offset": 50,
    "frame": 120,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      30
    ],
    "waitFrames": 30
  },
  {
    "offset": 53,
    "frame": 150,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      3
    ]
  },
  {
    "offset": 55,
    "frame": 150,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      1,
      0,
      0
    ],
    "actor": {
      "mode": 1,
      "slot": 0,
      "value": 0,
      "action": "reset"
    }
  },
  {
    "offset": 59,
    "frame": 150,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      1,
      1,
      0
    ],
    "actor": {
      "mode": 1,
      "slot": 1,
      "value": 0,
      "action": "reset"
    }
  },
  {
    "offset": 63,
    "frame": 150,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      0,
      0
    ],
    "actor": {
      "mode": 0,
      "slot": 0,
      "value": 0,
      "action": "startAnimation"
    }
  },
  {
    "offset": 67,
    "frame": 150,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      1,
      0
    ],
    "actor": {
      "mode": 0,
      "slot": 1,
      "value": 0,
      "action": "startAnimation"
    }
  },
  {
    "offset": 71,
    "frame": 150,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      2,
      0,
      0
    ],
    "actor": {
      "mode": 2,
      "slot": 0,
      "value": 0,
      "action": "setPoseFlag"
    }
  },
  {
    "offset": 75,
    "frame": 150,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      2,
      0,
      1
    ],
    "actor": {
      "mode": 2,
      "slot": 0,
      "value": 1,
      "action": "setPoseFlag"
    }
  },
  {
    "offset": 79,
    "frame": 150,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 83,
    "frame": 150,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      20
    ],
    "waitFrames": 20
  },
  {
    "offset": 86,
    "frame": 170,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      2,
      1,
      1
    ],
    "actor": {
      "mode": 2,
      "slot": 1,
      "value": 1,
      "action": "setPoseFlag"
    }
  },
  {
    "offset": 90,
    "frame": 170,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      4
    ],
    "waitFrames": 4
  },
  {
    "offset": 93,
    "frame": 174,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      2,
      1,
      0
    ],
    "actor": {
      "mode": 2,
      "slot": 1,
      "value": 0,
      "action": "setPoseFlag"
    }
  },
  {
    "offset": 97,
    "frame": 174,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 99,
    "frame": 174,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      0,
      1
    ],
    "actor": {
      "mode": 0,
      "slot": 0,
      "value": 1,
      "action": "startAnimation"
    }
  },
  {
    "offset": 103,
    "frame": 174,
    "opcode": 16,
    "name": "copyOverlayTransform",
    "handler": "0x801c8328",
    "payload": []
  },
  {
    "offset": 104,
    "frame": 174,
    "opcode": 15,
    "name": "toggleOverlay",
    "handler": "0x801c82b0",
    "payload": [
      1
    ]
  },
  {
    "offset": 106,
    "frame": 174,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      18
    ]
  },
  {
    "offset": 108,
    "frame": 174,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 112,
    "frame": 174,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 114,
    "frame": 174,
    "opcode": 17,
    "name": "rampOverlay",
    "handler": "0x801c835c",
    "payload": [
      0,
      8
    ]
  },
  {
    "offset": 117,
    "frame": 174,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      15
    ],
    "waitFrames": 15
  },
  {
    "offset": 120,
    "frame": 189,
    "opcode": 15,
    "name": "toggleOverlay",
    "handler": "0x801c82b0",
    "payload": [
      0
    ]
  },
  {
    "offset": 122,
    "frame": 189,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      1,
      1
    ],
    "actor": {
      "mode": 0,
      "slot": 1,
      "value": 1,
      "action": "startAnimation"
    }
  },
  {
    "offset": 126,
    "frame": 189,
    "opcode": 16,
    "name": "copyOverlayTransform",
    "handler": "0x801c8328",
    "payload": []
  },
  {
    "offset": 127,
    "frame": 189,
    "opcode": 15,
    "name": "toggleOverlay",
    "handler": "0x801c82b0",
    "payload": [
      1
    ]
  },
  {
    "offset": 129,
    "frame": 189,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      13
    ]
  },
  {
    "offset": 131,
    "frame": 189,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 135,
    "frame": 189,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 137,
    "frame": 189,
    "opcode": 17,
    "name": "rampOverlay",
    "handler": "0x801c835c",
    "payload": [
      0,
      8
    ]
  },
  {
    "offset": 140,
    "frame": 189,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      10
    ],
    "waitFrames": 10
  },
  {
    "offset": 143,
    "frame": 199,
    "opcode": 15,
    "name": "toggleOverlay",
    "handler": "0x801c82b0",
    "payload": [
      0
    ]
  },
  {
    "offset": 145,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      0,
      6
    ],
    "actor": {
      "mode": 0,
      "slot": 0,
      "value": 6,
      "action": "startAnimation"
    }
  },
  {
    "offset": 149,
    "frame": 199,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      20
    ]
  },
  {
    "offset": 151,
    "frame": 199,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 155,
    "frame": 199,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 157,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      1,
      6
    ],
    "actor": {
      "mode": 0,
      "slot": 1,
      "value": 6,
      "action": "startAnimation"
    }
  },
  {
    "offset": 161,
    "frame": 199,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      21
    ]
  },
  {
    "offset": 163,
    "frame": 199,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 167,
    "frame": 199,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 169,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      0,
      3
    ],
    "actor": {
      "mode": 0,
      "slot": 0,
      "value": 3,
      "action": "startAnimation"
    }
  },
  {
    "offset": 173,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      1,
      3
    ],
    "actor": {
      "mode": 0,
      "slot": 1,
      "value": 3,
      "action": "startAnimation"
    }
  },
  {
    "offset": 177,
    "frame": 199,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      15
    ]
  },
  {
    "offset": 179,
    "frame": 199,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      2,
      255,
      1
    ]
  },
  {
    "offset": 183,
    "frame": 199,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 185,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      1,
      4
    ],
    "actor": {
      "mode": 0,
      "slot": 1,
      "value": 4,
      "action": "startAnimation"
    }
  },
  {
    "offset": 189,
    "frame": 199,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      16
    ]
  },
  {
    "offset": 191,
    "frame": 199,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 195,
    "frame": 199,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 197,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      0,
      4
    ],
    "actor": {
      "mode": 0,
      "slot": 0,
      "value": 4,
      "action": "startAnimation"
    }
  },
  {
    "offset": 201,
    "frame": 199,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      19
    ]
  },
  {
    "offset": 203,
    "frame": 199,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 207,
    "frame": 199,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 209,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      0,
      7
    ],
    "actor": {
      "mode": 0,
      "slot": 0,
      "value": 7,
      "action": "startAnimation"
    }
  },
  {
    "offset": 213,
    "frame": 199,
    "opcode": 13,
    "name": "actorControl",
    "handler": "0x801c81a0",
    "payload": [
      0,
      1,
      7
    ],
    "actor": {
      "mode": 0,
      "slot": 1,
      "value": 7,
      "action": "startAnimation"
    }
  },
  {
    "offset": 217,
    "frame": 199,
    "opcode": 6,
    "name": "selectWidgetOrEffect",
    "handler": "0x801c7fc0",
    "payload": [
      17
    ]
  },
  {
    "offset": 219,
    "frame": 199,
    "opcode": 7,
    "name": "fade",
    "handler": "0x801c7ffc",
    "payload": [
      0,
      255,
      1
    ]
  },
  {
    "offset": 223,
    "frame": 199,
    "opcode": 8,
    "name": "setFadeTarget",
    "handler": "0x801c809c",
    "payload": [
      255
    ]
  },
  {
    "offset": 225,
    "frame": 199,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      60
    ],
    "waitFrames": 60
  },
  {
    "offset": 228,
    "frame": 259,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      9
    ]
  },
  {
    "offset": 230,
    "frame": 259,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      60
    ],
    "waitFrames": 60
  },
  {
    "offset": 233,
    "frame": 319,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      10
    ]
  },
  {
    "offset": 235,
    "frame": 319,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      60
    ],
    "waitFrames": 60
  },
  {
    "offset": 238,
    "frame": 379,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      11
    ]
  },
  {
    "offset": 240,
    "frame": 379,
    "opcode": 18,
    "name": "titleLightBar",
    "handler": "0x801c83b8",
    "payload": []
  },
  {
    "offset": 241,
    "frame": 379,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      0,
      150
    ],
    "waitFrames": 150
  },
  {
    "offset": 244,
    "frame": 529,
    "opcode": 0,
    "name": "setSceneStep",
    "handler": "0x801c7e64",
    "payload": [
      12
    ]
  },
  {
    "offset": 246,
    "frame": 529,
    "opcode": 19,
    "name": "spawnTitleWidget",
    "handler": "0x801c83e4",
    "payload": [
      0,
      29
    ]
  },
  {
    "offset": 249,
    "frame": 529,
    "opcode": 5,
    "name": "waitFrames",
    "handler": "0x801c7f70",
    "payload": [
      1,
      44
    ],
    "waitFrames": 300
  },
  {
    "offset": 252,
    "frame": 829,
    "opcode": 12,
    "name": "setAudioCue",
    "handler": "0x801c8168",
    "payload": [
      0
    ]
  },
  {
    "offset": 254,
    "frame": 829,
    "opcode": 4,
    "name": "end",
    "handler": "0x801c7f4c",
    "payload": []
  }
] as const;

export const TITLE_INTRO_ACTOR_EVENTS = [
  {
    "frame": 150,
    "offset": 63,
    "slot": 0,
    "actionGroup": 5,
    "animId": 0,
    "assetGroup": 0,
    "assetSlot": 0,
    "label": "idle",
    "file": "anim_g00_s00_idle.json"
  },
  {
    "frame": 150,
    "offset": 67,
    "slot": 1,
    "actionGroup": 5,
    "animId": 0,
    "assetGroup": 0,
    "assetSlot": 0,
    "label": "idle",
    "file": "anim_g00_s00_idle.json"
  },
  {
    "frame": 174,
    "offset": 99,
    "slot": 0,
    "actionGroup": 5,
    "animId": 1,
    "assetGroup": 0,
    "assetSlot": 1,
    "label": "move",
    "file": "anim_g00_s01_move.json"
  },
  {
    "frame": 189,
    "offset": 122,
    "slot": 1,
    "actionGroup": 5,
    "animId": 1,
    "assetGroup": 0,
    "assetSlot": 1,
    "label": "move",
    "file": "anim_g00_s01_move.json"
  },
  {
    "frame": 199,
    "offset": 145,
    "slot": 0,
    "actionGroup": 5,
    "animId": 6,
    "assetGroup": 0,
    "assetSlot": 6,
    "label": "jump_takeoff",
    "file": "anim_g00_s06_jump_takeoff.json"
  },
  {
    "frame": 199,
    "offset": 157,
    "slot": 1,
    "actionGroup": 5,
    "animId": 6,
    "assetGroup": 0,
    "assetSlot": 6,
    "label": "jump_takeoff",
    "file": "anim_g00_s06_jump_takeoff.json"
  },
  {
    "frame": 199,
    "offset": 169,
    "slot": 0,
    "actionGroup": 5,
    "animId": 3,
    "assetGroup": 0,
    "assetSlot": 3,
    "label": "dash_back",
    "file": "anim_g00_s03_dash_back.json"
  },
  {
    "frame": 199,
    "offset": 173,
    "slot": 1,
    "actionGroup": 5,
    "animId": 3,
    "assetGroup": 0,
    "assetSlot": 3,
    "label": "dash_back",
    "file": "anim_g00_s03_dash_back.json"
  },
  {
    "frame": 199,
    "offset": 185,
    "slot": 1,
    "actionGroup": 5,
    "animId": 4,
    "assetGroup": 0,
    "assetSlot": 4,
    "label": "dash_left",
    "file": "anim_g00_s04_dash_left.json"
  },
  {
    "frame": 199,
    "offset": 197,
    "slot": 0,
    "actionGroup": 5,
    "animId": 4,
    "assetGroup": 0,
    "assetSlot": 4,
    "label": "dash_left",
    "file": "anim_g00_s04_dash_left.json"
  },
  {
    "frame": 199,
    "offset": 209,
    "slot": 0,
    "actionGroup": 5,
    "animId": 7,
    "assetGroup": 0,
    "assetSlot": 7,
    "label": "jump_land",
    "file": "anim_g00_s07_jump_land.json"
  },
  {
    "frame": 199,
    "offset": 213,
    "slot": 1,
    "actionGroup": 5,
    "animId": 7,
    "assetGroup": 0,
    "assetSlot": 7,
    "label": "jump_land",
    "file": "anim_g00_s07_jump_land.json"
  }
] as const;

export const TITLE_INTRO_TOTAL_FRAMES = 829 as const;
