// =============================================================================
// inventory.generated.ts — GENERATED by scripts/gx-call-inventory.mjs.
// DO NOT EDIT BY HAND; re-run the script instead.
//
// The measured GX call surface of Gotcha Force: every GX entry point that ROM
// GAME code calls, ranked by static call-site count. This is the ranked list
// the HLE host's GX work is prioritized by, and the denominator its coverage
// percentage is computed against — so the coverage number is derived from a
// measurement rather than asserted.
//
// HONESTY NOTE (repeated from the generator): these are STATIC call-site
// counts — how many places in the ROM call an entry point, not how often it
// executes. A per-frame frequency ranking requires a Dolphin trace and does
// not exist yet.
//
// Corpus: research/decomp/ghidra-export
// GX symbols in the DOL: 157
// Called by game code:   76
// Game call sites:       502
// =============================================================================

export interface GxInventoryEntry {
  /** The C symbol as it appears in the corpus (and as a wasm import name). */
  readonly symbol: string;
  /** The entry point's real GameCube address in this game's DOL. */
  readonly romAddr: number | null;
  /** Static call sites in ROM game code — the ranking key. */
  readonly gameCalls: number;
  /** Static call sites inside other gnt4_* SDK/HSD functions (context only). */
  readonly sdkInternalCalls: number;
  /** Distinct ROM functions that call it. */
  readonly distinctGameCallers: number;
}

/** GX entry points called by ROM game code, ranked by static call sites. */
export const GX_CALL_INVENTORY: readonly GxInventoryEntry[] = [
  { symbol: "gnt4_GXSetVtxDesc_bl", romAddr: 0x80225894, gameCalls: 45, sdkInternalCalls: 4, distinctGameCallers: 18 },
  { symbol: "gnt4_GXSetVtxAttrFmt_bl", romAddr: 0x802261e4, gameCalls: 45, sdkInternalCalls: 3, distinctGameCallers: 18 },
  { symbol: "gnt4_GXBegin_bl", romAddr: 0x8022760c, gameCalls: 19, sdkInternalCalls: 1, distinctGameCallers: 17 },
  { symbol: "gnt4_GXSetTevOrder_bl", romAddr: 0x8022a14c, gameCalls: 18, sdkInternalCalls: 16, distinctGameCallers: 15 },
  { symbol: "gnt4_GXClearVtxDesc_bl", romAddr: 0x802261ac, gameCalls: 18, sdkInternalCalls: 4, distinctGameCallers: 18 },
  { symbol: "gnt4_GXSetProjection_bl", romAddr: 0x8022bce8, gameCalls: 18, sdkInternalCalls: 4, distinctGameCallers: 16 },
  { symbol: "gnt4_GXSetZMode_bl", romAddr: 0x8022a8b4, gameCalls: 18, sdkInternalCalls: 2, distinctGameCallers: 15 },
  { symbol: "gnt4_GXEnableTexOffsets_bl", romAddr: 0x802277e4, gameCalls: 16, sdkInternalCalls: 8, distinctGameCallers: 2 },
  { symbol: "gnt4_GXLoadPosMtxImm_bl", romAddr: 0x8022be60, gameCalls: 16, sdkInternalCalls: 6, distinctGameCallers: 15 },
  { symbol: "gnt4_GXSetChanCtrl_bl", romAddr: 0x80228898, gameCalls: 16, sdkInternalCalls: 2, distinctGameCallers: 14 },
  { symbol: "gnt4_GXSetCurrentMtx_bl", romAddr: 0x8022bf00, gameCalls: 15, sdkInternalCalls: 4, distinctGameCallers: 15 },
  { symbol: "gnt4_GXSetNumChans_bl", romAddr: 0x8022885c, gameCalls: 15, sdkInternalCalls: 2, distinctGameCallers: 15 },
  { symbol: "gnt4_GXSetNumTevStages_bl", romAddr: 0x8022a2e8, gameCalls: 15, sdkInternalCalls: 2, distinctGameCallers: 15 },
  { symbol: "gnt4_GXSetNumTexGens_bl", romAddr: 0x80226d6c, gameCalls: 15, sdkInternalCalls: 2, distinctGameCallers: 15 },
  { symbol: "gnt4_GXSetCullMode_bl", romAddr: 0x8022782c, gameCalls: 14, sdkInternalCalls: 2, distinctGameCallers: 14 },
  { symbol: "gnt4_GXSetTevOp_bl", romAddr: 0x80229bac, gameCalls: 13, sdkInternalCalls: 2, distinctGameCallers: 13 },
  { symbol: "gnt4_GXSetTexCoordGen2_bl", romAddr: 0x80226aec, gameCalls: 9, sdkInternalCalls: 14, distinctGameCallers: 8 },
  { symbol: "gnt4_GXLoadTexObj_bl", romAddr: 0x80229108, gameCalls: 9, sdkInternalCalls: 9, distinctGameCallers: 8 },
  { symbol: "gnt4_GXSetTevKColor_bl", romAddr: 0x80229e88, gameCalls: 9, sdkInternalCalls: 1, distinctGameCallers: 4 },
  { symbol: "gnt4_GXLoadTexMtxImm_bl", romAddr: 0x8022bf34, gameCalls: 8, sdkInternalCalls: 13, distinctGameCallers: 8 },
  { symbol: "gnt4_GXSetBlendMode_bl", romAddr: 0x8022a808, gameCalls: 8, sdkInternalCalls: 2, distinctGameCallers: 8 },
  { symbol: "gnt4_GXInitTexObjLOD_bl", romAddr: 0x80228e08, gameCalls: 8, sdkInternalCalls: 0, distinctGameCallers: 6 },
  { symbol: "gnt4_GXSetTevKColorSel_bl", romAddr: 0x80229efc, gameCalls: 7, sdkInternalCalls: 2, distinctGameCallers: 4 },
  { symbol: "gnt4_GXSetTevAlphaOp_bl", romAddr: 0x80229d28, gameCalls: 7, sdkInternalCalls: 0, distinctGameCallers: 4 },
  { symbol: "gnt4_GXSetTevColorIn_bl", romAddr: 0x80229c38, gameCalls: 7, sdkInternalCalls: 0, distinctGameCallers: 4 },
  { symbol: "gnt4_GXSetTevColorOp_bl", romAddr: 0x80229cc0, gameCalls: 7, sdkInternalCalls: 0, distinctGameCallers: 4 },
  { symbol: "gnt4_GXInvalidateTexAll_bl", romAddr: 0x80229358, gameCalls: 6, sdkInternalCalls: 2, distinctGameCallers: 6 },
  { symbol: "gnt4_GXSetTevSwapMode_bl", romAddr: 0x80229fb4, gameCalls: 5, sdkInternalCalls: 2, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetTevColor_bl", romAddr: 0x80229d90, gameCalls: 5, sdkInternalCalls: 1, distinctGameCallers: 3 },
  { symbol: "gnt4_GXSetTevAlphaIn_bl", romAddr: 0x80229c7c, gameCalls: 5, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetArray", romAddr: 0x80226a50, gameCalls: 4, sdkInternalCalls: 3, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetAlphaUpdate_bl", romAddr: 0x8022a888, gameCalls: 4, sdkInternalCalls: 2, distinctGameCallers: 3 },
  { symbol: "gnt4_GXSetColorUpdate_bl", romAddr: 0x8022a85c, gameCalls: 4, sdkInternalCalls: 2, distinctGameCallers: 3 },
  { symbol: "gnt4_GXSetTevSwapModeTable_bl", romAddr: 0x80229ffc, gameCalls: 3, sdkInternalCalls: 4, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitTexObj_bl", romAddr: 0x80228b74, gameCalls: 3, sdkInternalCalls: 2, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetTevKAlphaSel_bl", romAddr: 0x80229f58, gameCalls: 3, sdkInternalCalls: 2, distinctGameCallers: 1 },
  { symbol: "gnt4_GXLoadTlut_bl", romAddr: 0x80229194, gameCalls: 3, sdkInternalCalls: 1, distinctGameCallers: 3 },
  { symbol: "gnt4_GXSetVtxAttrFmtv_bl", romAddr: 0x80226440, gameCalls: 3, sdkInternalCalls: 1, distinctGameCallers: 3 },
  { symbol: "gnt4_GXProject_bl", romAddr: 0x8022bb74, gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 3 },
  { symbol: "gnt4_GXSetCPUFifo_bl", romAddr: 0x80225378, gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetGPFifo_bl", romAddr: 0x802254a0, gameCalls: 3, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4___GXFlushTextureState_bl", romAddr: 0x80229b88, gameCalls: 2, sdkInternalCalls: 6, distinctGameCallers: 1 },
  { symbol: "gnt4_GXPixModeSync_bl", romAddr: 0x80227240, gameCalls: 2, sdkInternalCalls: 4, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetChanMatColor_bl", romAddr: 0x8022876c, gameCalls: 2, sdkInternalCalls: 4, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetFog_bl", romAddr: 0x8022a310, gameCalls: 2, sdkInternalCalls: 3, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetFogRangeAdj_bl", romAddr: 0x8022a6e4, gameCalls: 2, sdkInternalCalls: 3, distinctGameCallers: 2 },
  { symbol: "gnt4_GXInvalidateVtxCache_bl", romAddr: 0x80226adc, gameCalls: 2, sdkInternalCalls: 2, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetAlphaCompare_bl", romAddr: 0x8022a07c, gameCalls: 2, sdkInternalCalls: 2, distinctGameCallers: 2 },
  { symbol: "gnt4_GXGetGPFifo_bl", romAddr: 0x8022588c, gameCalls: 2, sdkInternalCalls: 1, distinctGameCallers: 2 },
  { symbol: "gnt4_GXGetProjectionv_bl", romAddr: 0x8022be18, gameCalls: 2, sdkInternalCalls: 1, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetLineWidth_bl", romAddr: 0x80227764, gameCalls: 2, sdkInternalCalls: 1, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetPointSize_bl", romAddr: 0x802277a4, gameCalls: 2, sdkInternalCalls: 1, distinctGameCallers: 2 },
  { symbol: "gnt4_GXCopyTex_bl", romAddr: 0x80228188, gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_GXInitTlutRegion_bl", romAddr: 0x80229320, gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetTexCopyDst_bl", romAddr: 0x80227b14, gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 2 },
  { symbol: "gnt4_GXSetTexCopySrc_bl", romAddr: 0x80227a64, gameCalls: 2, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitLightColor_bl", romAddr: 0x802285f4, gameCalls: 1, sdkInternalCalls: 7, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitLightPos_bl", romAddr: 0x802285c8, gameCalls: 1, sdkInternalCalls: 6, distinctGameCallers: 1 },
  { symbol: "gnt4_GXLoadNrmMtxImm_bl", romAddr: 0x8022beb0, gameCalls: 1, sdkInternalCalls: 6, distinctGameCallers: 1 },
  { symbol: "gnt4_GXLoadLightObjImm_bl", romAddr: 0x80228600, gameCalls: 1, sdkInternalCalls: 5, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitLightDistAttn_bl", romAddr: 0x802284f8, gameCalls: 1, sdkInternalCalls: 4, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetChanAmbColor_bl", romAddr: 0x8022867c, gameCalls: 1, sdkInternalCalls: 4, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetScissor_bl", romAddr: 0x8022c13c, gameCalls: 1, sdkInternalCalls: 4, distinctGameCallers: 1 },
  { symbol: "gnt4_GXGetViewportv_bl", romAddr: 0x8022c118, gameCalls: 1, sdkInternalCalls: 2, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitLightSpot_bl", romAddr: 0x80228368, gameCalls: 1, sdkInternalCalls: 2, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitTlutObj_bl", romAddr: 0x8022915c, gameCalls: 1, sdkInternalCalls: 1, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetCopyFilter_bl", romAddr: 0x80227e04, gameCalls: 1, sdkInternalCalls: 1, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetNumIndStages_bl", romAddr: 0x80229ae8, gameCalls: 1, sdkInternalCalls: 1, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetTevColorS10_bl", romAddr: 0x80229e0c, gameCalls: 1, sdkInternalCalls: 1, distinctGameCallers: 1 },
  { symbol: "gnt4___GXFifoInit_bl", romAddr: 0x8022565c, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4___GXInitGX_bl", romAddr: 0x80224824, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4___GXPEInit_bl", romAddr: 0x80227518, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4___GXSetIndirectMask_bl", romAddr: 0x80229b58, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4___GXSetTmemConfig_bl", romAddr: 0x802295e4, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_GXInitFifoBase_bl", romAddr: 0x80225290, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
  { symbol: "gnt4_GXSetMisc_bl", romAddr: 0x80226da8, gameCalls: 1, sdkInternalCalls: 0, distinctGameCallers: 1 },
];

/** Total static game-code call sites across the whole ranked surface. */
export const GX_GAME_CALL_SITES = 502;

/** Look one entry point up by symbol. */
export function gxInventoryEntry(symbol: string): GxInventoryEntry | undefined {
  return GX_CALL_INVENTORY.find((e) => e.symbol === symbol);
}

/**
 * Coverage of the ranked surface, by BOTH measures that matter:
 * how many distinct entry points are implemented, and what share of the
 * ROM's static call sites they account for (weighted coverage). The second
 * is the honest headline: implementing the top ten entry points covers far
 * more of the ROM's actual GX usage than 10/76 suggests.
 */
export function gxCoverage(implemented: Iterable<string>): {
  implementedSymbols: number;
  totalSymbols: number;
  symbolPct: number;
  coveredCallSites: number;
  totalCallSites: number;
  callSitePct: number;
} {
  const set = new Set(implemented);
  const covered = GX_CALL_INVENTORY.filter((e) => set.has(e.symbol));
  const coveredCallSites = covered.reduce((sum, e) => sum + e.gameCalls, 0);
  return {
    implementedSymbols: covered.length,
    totalSymbols: GX_CALL_INVENTORY.length,
    symbolPct: Math.round((covered.length / GX_CALL_INVENTORY.length) * 1000) / 10,
    coveredCallSites,
    totalCallSites: GX_GAME_CALL_SITES,
    callSitePct: Math.round((coveredCallSites / GX_GAME_CALL_SITES) * 1000) / 10,
  };
}
